### ISSUE TITLE
Update node-jscs to 1.4.x and enjoy presets

### ISSUE THREAD

**Issue by lijunle** [AtomLinter/linter-jscs#10]
With 1.4.x release, node-jscs has prepared some predefined rules as a preset. https://github.com/mdevils/node-jscs/tree/master/presets

First, update to 1.4.x to enjoy new features.

Second, add a drop down list in atom setting view to let the user choose a preset. We can provide three modes:

0. Use a preset
0. Use customer defined rules
0. User a preset and overwrite the rule if the user defined it

@iam4x How do you think about this as an enhancement?

**Comment by iam4x** [comment]
@lijunle Added a drop down select with https://github.com/AtomLinter/linter-jscs/commit/31c7d92018895e161dde5b00bf17b3bb1658b718

I close the issue.

**Comment by lijunle** [comment]
That is a great news. Atom finally support enum configuration :)
