### ISSUE TITLE
HTML in editor report

### ISSUE THREAD

**Issue by WillsB3** [AtomLinter/linter-jscs#100]
Any idea what's going on here?

<img width="742" alt="screen shot 2015-08-27 at 19 25 55" src="https://cloud.githubusercontent.com/assets/868834/9529441/30b77414-4cf2-11e5-80e9-083ac5d270e4.png">

**Comment by casesandberg** [comment]
I believe this was a rendering error on Atom's part that has been fixed. Are you still seeing this issue?

**Comment by Arcanemagus** [comment]
If you are still seeing this please file an issue on the [linter package](https://github.com/atom-community/linter/), this package has nothing to do with the UI beyond supplying the contents of the messages :wink:.
