### ISSUE TITLE
Error on all 'use strict' declarations saying something about disalowSpaceAfterObjectKeys

### ISSUE THREAD

**Issue by gnomeontherun** [AtomLinter/linter-jscs#107]
The error is below, says it is a problem with JSCS and not my codebase. This happened after a recent update to the linter-jscs package.

<img width="1215" alt="screen shot 2015-09-10 at 5 06 43 pm" src="https://cloud.githubusercontent.com/assets/79500/9802256/6a7c1bc2-57de-11e5-9f11-0ba4d99cc89c.png">

**Comment by casesandberg** [comment]
I saw this back when you were seeing it, but I dont see it anymore. Are you still having issues with this?

**Comment by gnomeontherun** [comment]
No, I haven't seen it recently either, thanks for checking. Closing.
