### ISSUE TITLE
Switching between ES5 and ES6

### ISSUE THREAD

**Issue by imalitavakoli** [AtomLinter/linter-jscs#112]
Is there any possible solution to disable linter-jscs when we're viewing a ES5 .js file, so that it doesn't show errors on our file?

And yes! It doesn't matter if I remove the config file(.jshintrc) for the jscs... As far as the linter-jscs package is enable, it shows errors on ES5 Javascript files!

This issue is somehow similar to this one: https://github.com/AtomLinter/linter-jscs/issues/18

But the difference is that I'd like to view both(ES5, ES6) files in the SAME project.
Right now whenever I open my ES5 file, I have to disable the linter-jscs package and enable it again when I switch to ES6... This is tedious!

Is there a solution or something that I'm not seeing?
Thanks.

**Comment by casesandberg** [comment]
The package lints all js files, there is no way for atom to know that your file is ES5 / ES6 and conditionally apply it. 

You can, however, move your ES5 files into a specific folder and just exlude that folder from being linted: http://jscs.info/overview#excludefiles
