### ISSUE TITLE
Allow usage of project-specific version of jscs

### ISSUE THREAD

**Issue by DjebbZ** [AtomLinter/linter-jscs#114]
Hello,

I'm joining a project where there's already a version of jscs used through the package.json. It's older than the internal jscs version used by linter-jscs, therefore there's a rule which changed name and linter-jscs reports a false negative.

To be precise, the project is using jscs through the grunt-jscs plugin.

Is it possible to use the version of jscs installed in the project by default, and fallback with the version that ships with linter-jscs ? [linter-eslint](https://github.com/AtomLinter/linter-eslint) does this and I think it's a great feature.

Thanks in advance !

**Comment by DjebbZ** [comment]
I just found that linter-jshint allows to specify the path to the jshint executable. Solves the problem of jshint wrappers like gulp, grunt, etc.

**Comment by donaldpipowitch** [comment]
In WebStorm you can add a JSCS package path like `node_modules/jscs/`. It would be nice, if `linter-jscs`would offer the same.

**Comment by casesandberg** [comment]
I am not really sure how to implement something like this. Maybe it would be easier for you to just fork the plugin and change the `jscs` version in `package.json` and use your local version.

**Comment by Arcanemagus** [comment]
You can add a simple path setting like above, or attempt to figure out the correct path on your own like we do over in `linter-eslint`, but it's a _huge_ pain to get right.

**Comment by trvra** [comment]
I've had a similar issue for a while now. For whatever reason my group is fixed on jscs 1.13.1. My approach has been:

* update linter-jscs as needed
* navigate to `~/.atom/packages/linter-jscs/`
* edit `package.json` for linter-jscs to modify the dependency requirement of jscs to your specific version
* `npm install` in `~/.atom/packages/linter-jscs`
* reload Atom

Repeat this process each time linter-jscs updates. I found these extra steps were enough to keep me from updating linter-jscs frequently, but it's enough to keep your stuff linted within Atom.

**Comment by Arcanemagus** [comment]
Marking this as closed, JSCS development is dead, and it seems none of the people still using it are interested in implementing this functionality.
