### ISSUE TITLE
Fix on save doesn't work if there's more than 50 errors

### ISSUE THREAD

**Issue by scholtzm** [AtomLinter/linter-jscs#121]
Fix on save doesn't work if there's more than 50 errors. On the other hand, if I run `jscs -x fileName.js`, that works as expected.

**Comment by casesandberg** [comment]
This seems to be an error where atom caps out on the number of errros it will display for one file. Looking into a solution for this.

**Comment by casesandberg** [comment]
Update: Seems to be jscs not atom, looks like the `fixString` helper in `node-jscs` is shitting the bed.

**Comment by casesandberg** [comment]
I can confirm this is an issue with `node-jscs`

**Comment by Arcanemagus** [comment]
If this is an issue with `node-jscs` an issue should be filed over there.
