### ISSUE TITLE
"Only Config" setting don't work

### ISSUE THREAD

**Issue by Sundae** [AtomLinter/linter-jscs#124]
I've checked the "Only Config" setting and there is no .jscsrc config in my project, but it is not disabled.

![2015-10-22 6 00 44](https://cloud.githubusercontent.com/assets/1232693/10662396/eb7853de-78e6-11e5-9e85-4b552de76e99.png)
![2015-10-22 6 00 55](https://cloud.githubusercontent.com/assets/1232693/10662397/eb7e0c98-78e6-11e5-95a9-ac46dd9a63bd.png)

**Comment by trvra** [comment]
I'm seeing this issue as well...

![screen shot 2016-01-20 at 11 18 09 am](https://cloud.githubusercontent.com/assets/2667129/12461028/a49b0238-bf6b-11e5-8cee-8d52628e27ba.png)

![screen shot 2016-01-20 at 11 59 21 am](https://cloud.githubusercontent.com/assets/2667129/12461361/57242578-bf6d-11e5-92dc-ad13646aa89d.png)

Did you find a workaround? I'm looking into the codebase to see if I can't sort out what's going wrong, I bet a PR is in order...

**Comment by Arcanemagus** [comment]
What is the value of `config` at [this point](https://github.com/AtomLinter/linter-jscs/blob/v3.4.1/src/linter-jscs.js#L123)?

**Comment by trvra** [comment]
@Arcanemagus Turns out, I had a .jscsrc file in my home directory that I didn't know existed. It was being picked up by the `findup` method in jscs. Sorry for the invalid bump of a closed topic 😓

**Comment by casesandberg** [comment]
Ah, good to hear! Just happy I'm not going crazy or something like that.

**Comment by Arcanemagus** [comment]
Marking invalid as I'm assuming there was a similar situation with @Sundae :wink:.
