### ISSUE TITLE
error loop regarding javasript object in array

### ISSUE THREAD

**Issue by clementmiao** [AtomLinter/linter-jscs#126]
Below is a screenshot of the issue I was having, where it indicates to me that there is a missing comma before closing beracket.

![image of issue](https://www.dropbox.com/s/2owvt0sh4l4lhrm/Screenshot%202015-10-22%2022.33.25.png?dl=1)

So I added the the missing comma, so that line 10 has the error fixed:
![image of step 2](https://www.dropbox.com/s/nqfhdpu78tit66t/Screenshot%202015-10-22%2022.35.53.png?dl=1)

I then get a second error, 'Space required after comma', as indicated.

Once I fixed that, I get the last error:
![last error](https://www.dropbox.com/s/9vqvnsqr2bkl0j5/Screenshot%202015-10-22%2022.37.27.png?dl=1)

As you can see, this is a loop of errors since I remove the space, I get back to the second error.

**Comment by Arcanemagus** [comment]
You probably want to file this over on the [jscs](https://github.com/jscs-dev/node-jscs) repository, this package merely runs `jscs` and reports the results.

Marking this as closed, but if for some bizarre reason it is this package feel free to reopen it.

**Comment by clementmiao** [comment]
Thanks. I have filed this at the node-jscs repository.

I'll reopen this if it's a linter-jscs issue. Sorry for the trouble!

**Comment by Arcanemagus** [comment]
No worries, thanks for taking the time to report it :wink:.
