### ISSUE TITLE
Allow setting path to configuration file.

### ISSUE THREAD

**Issue by donaldpipowitch** [AtomLinter/linter-jscs#127]
WebStorm allows settings the path to configuration file like `node_modules/company-style/.jscsrc`. It would be nice if `linter-jscs` could do the same.

**Comment by dacodekid** [comment]
+1. I was going to ask this, then thought to give it a try. @iam4x just in case, if you are interested, plz consider this PR - https://github.com/AtomLinter/linter-jscs/pull/129

**Comment by otbe** [comment]
:+1:

**Comment by iam4x** [comment]
I think @Arcanemagus is waiting for changes on @dacodekid PR and it will be merged :

**Comment by dacodekid** [comment]
Sorry, but missed @Arcanemagus 's notification. Unfortunately I moved on and started using [XO] (https://github.com/sindresorhus/xo). Hope @iam4x or @Arcanemagus makes the necessary changes.

**Comment by donaldpipowitch** [comment]
Yeah, it would be nice if @Arcanemagus could make the changes.

**Comment by Arcanemagus** [comment]
This is published in v3.2.0, I don't use this plugin either myself so it hasn't been thoroughly tested, please file an issue if it doesn't work properly for you.
