### ISSUE TITLE
Parse error if file is deleted but still open

### ISSUE THREAD

**Issue by adamkdean** [AtomLinter/linter-jscs#131]
There is a bug with deleting open files in Atom 1.1.0 with linter-jscs 3.1.2 & 3.2.0.

How to reproduce:

1. Create test.js
2. Line 1, `export const SOME_TEXT = 'whatever'`
3. Delete test.js
4. In still open tab, write something else. You'll now get a parse error due to EOF.

![screen shot 2015-11-05 at 10 30 37](https://cloud.githubusercontent.com/assets/1639527/10965965/4c591eba-83a8-11e5-8801-8b0d4bf1d5e8.png)

**Comment by casesandberg** [comment]
I can't seem to reproduce this anymore. Do you still see this happening?

**Comment by casesandberg** [comment]
Marking as closed as I can not reproduce this. If you are still having issues please re-open.
