### ISSUE TITLE
Keyboard shortcut to fix file and to save without fixing

### ISSUE THREAD

**Issue by ProLoser** [AtomLinter/linter-jscs#132]
This way I can fix a file if I want to when `fix on save` is disabled and I can save changes without completely rewriting a file if I have `fix on save` enabled.

Perhaps CMD+SHIFT+S or something

**Comment by lnfnunes** [comment]
To achieve this, I've been using this other plugin https://github.com/foliveira/jscs-fixer.
It have a right click menu context "Fix this file" option and "(CTRL/CMD)+SHIFT+J" keyboard shortcut.
Maybe it's a good idea to have it "native" with only one plugin.
+1

**Comment by Arcanemagus** [comment]
@ProLoser your second case would be covered by simply disabling the Fix on Save option.

**Comment by Arcanemagus** [comment]
Marking this as closed, JSCS development is dead, and it seems none of the people still using it are interested in implementing this functionality.
