### ISSUE TITLE
excludeFiles with preset not excluding files

### ISSUE THREAD

**Issue by raido** [AtomLinter/linter-jscs#134]
I have a simple .jscsrc file:

```
{
  "preset": "ember-suave",
  "excludeFiles": ["vendor/**"]
}
```

When i remove preset from the file, Atom will obey excludeFiles patterns. When i add preset back it tries to lint all the vendor files.

Running # jscs from command line works fine.

**Comment by Arcanemagus** [comment]
We simply call the `jscs` function [here](https://github.com/AtomLinter/linter-jscs/blob/master/index.js#L107) to have it grab the config, so I'm not sure why this would be happening...

**Comment by raido** [comment]
```
JSCS: ()
config: Object
configPath: "/PathToMyApp/.jscsrc"
excludeFiles: Array[1]
0: "./vendor/**"
length: 1
__proto__: Array[0]
preset: "ember-suave"
__proto__: Object
editor: TextEditor
```

**Comment by casesandberg** [comment]
The `jscs-node` plugin knows nothing about files because you are using its `checkString` method. I went ahead and put in some code that checks the file paths against the `excludeFiles` array in the config and will skip showing errors and fixing them on save!
