### ISSUE TITLE
AssertionError: requireCamelCaseOrUpperCaseIdentifiers requires ignoreProperties

### ISSUE THREAD

**Issue by amyrlam** [AtomLinter/linter-jscs#135]
This error keeps popping up, not sure how to fix?

Assertion Error: requireCamelCaseOrUpperCaseIdentifiers option requires a true value or `ignoreProperties`.

My `.jscsrc` has:

```
"requireCamelCaseOrUpperCaseIdentifiers": {
  "ignoreProperties": true,
  "strict": false
}
```

which is up to date per: https://github.com/jscs-dev/node-jscs/commit/4e04449ee01ba628a8481165a6f060f017a4d803

![image](https://cloud.githubusercontent.com/assets/1372946/11517720/2ce1ecb8-9840-11e5-8c35-3908655a23e6.png)

Atom packages I'm using: linter, linter-jscs, linter-jshint, merge-conflicts. Atom and all packages up to date, on Mac OS X 10.11.1. Doesn't seem to change if I disable/uninstall merge-conflicts package.

Let me know if you have any debugging ideas or need more info!

**Comment by casesandberg** [comment]
Can you do me a favour and upgrade to the newest version of the package and see if it is still giving you issues?

**Comment by casesandberg** [comment]
Marking as closed as I can not reproduce this. If you are still having issues please re-open.
