### ISSUE TITLE
Invalid line break error comes up in windows

### ISSUE THREAD

**Issue by magestican** [AtomLinter/linter-jscs#139]
I am getting : 
validateLineBreaks : Invalid line break on my javascript files using atom on windows in the first line of every file.

The version I have of linter-jscs is 3.2.0.

Could you add support for windows? Thank you.

**Comment by Arcanemagus** [comment]
I'm pretty sure you are talking about the [validateLineBreaks](http://jscs.info/rule/validateLineBreaks.html) rule in JSCS, which most likely defaults to LF. You can change the file to the correct line ending by clicking on the "CRLF" that should be in your status bar.

Marking this as closed as this isn't an issue.

**Comment by srbalakkl** [comment]
It come even after clicking of **"CRLF"**
