### ISSUE TITLE
JSX is not ignored despite setting `validateQuoteMarks.ignoreJSX` to `true`

### ISSUE THREAD

**Issue by engelfrost** [AtomLinter/linter-jscs#140]
Double quotes in my JSX is not being ignored. 

DummySpan.jsx: 
```javascript
import React from 'react';

export default function DummySpan() {
  return <span className="dummy"></span>; // linter-jscs wants to fix these double quotes instead of ignoring them
}
```

.jscsrc: 
```json
{
  "esnext": true,
  "validateQuoteMarks": {
    "mark": "'",
    "escape": true,
    "ignoreJSX": true
  }
}
```

I'm using linter-jscs 3.2.0. 

From what I can tell the problem does not seem to be with JSCS itself. If I run `jscs --config ./.jscsrc --verbose DummySpan.jsx` (using jscs 2.5.0 or jscs 2.6.0) I get not errors from JSCS. If I run it with the `--fix` command, nothing gets fixed by JSCS.

**Comment by engelfrost** [comment]
Adding the `"esprima" : "esprima-fb"` option solves this issue. I have not bothered to find out why this is not necessary when running from the CLI. 

```json
{
  "esnext": true,
  "esprima" : "esprima-fb",
  "validateQuoteMarks": {
    "mark": "'",
    "escape": true,
    "ignoreJSX": true
  }
}
```

**Comment by Arcanemagus** [comment]
That's certainly bizarre, glad you figured it out though.
