### ISSUE TITLE
Unexpected indentation of 2 characters

### ISSUE THREAD

**Issue by RystLee** [AtomLinter/linter-jscs#141]
how to change it as 4...

**Comment by SpainTrain** [comment]
In `.jscsrc`:

```json
{
    "validateIndentation": 4
}
```

It's not very clear from the docs :-/ (http://jscs.info/rule/validateIndentation) but this works.

**Comment by Arcanemagus** [comment]
Marking as closed since this isn't an issue with `linter-jscs`, feel free to keep discussing though :wink:.
