### ISSUE TITLE
"Only Config" setting doesn't function. Option is ignored.

### ISSUE THREAD

**Issue by jtokoph** [AtomLinter/linter-jscs#150]
The conditional that checks if a config is missing points to a non existent property `this.isMissingConfig`:

https://github.com/AtomLinter/linter-jscs/blob/2cc36f1c1704ec5ddcbc7a1b702f0659e4513cb6/index.js#L143

As far as I can tell, this can never be truthy.

**Comment by Arcanemagus** [comment]
Looks like it should be working fine in the [lint section](https://github.com/AtomLinter/linter-jscs/blob/2cc36f1c1704ec5ddcbc7a1b702f0659e4513cb6/index.js#L117), but does seem to be broken in the fix section as you pointed out. I'm guessing a refactor somewhere messed this up. Would be nice to review a PR that configures `jscs` in the fixString area.

**Comment by casesandberg** [comment]
This has been fixed in `v3.3.0`
