### ISSUE TITLE
Implement specs

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-jscs#155]
It looks like this linter does not currently have any specs written for it, adding it to the list being maintained [here](https://github.com/AtomLinter/Meta/issues/11) for tracking.

Specs do not need to be super detailed, as they should mainly test whether the package is properly running the linter plugin and parsing its messages. Leave testing of the linter functionality to the author of the linter.

If you need any help feel free to ask!

**Comment by casesandberg** [comment]
I started work on that last night on the `spec` branch https://github.com/AtomLinter/linter-jscs/tree/tests. I have the very basic specs that all the other linters have, but I am going to put some more robust ones in there tonight before merging it in.

**Comment by Arcanemagus** [comment]
I just blanket submitted this to all repos that didn't have a `spec` folder :wink:

You should check out that tracking issue lol... the list is _huge_ :disappointed:.

**Comment by casesandberg** [comment]
Yeah I figured :+1: 

If I am ever in a testing mood one day I might go through and just dump basic ones in there for a bunch :8ball:

**Comment by Arcanemagus** [comment]
Yea, I'll probably be getting to them eventually, but I think I'm going to focus on https://github.com/AtomLinter/Meta/issues/9 first, since completely broken is worse than not being tested.

**Comment by casesandberg** [comment]
I might be able to take over https://github.com/AtomLinter/linter-jsxhint too, I am interested in anything JavaScript / react related

**Comment by casesandberg** [comment]
Will look into it tonight!

**Comment by Arcanemagus** [comment]
Actually it looks like JSXHint itself is deprecated, so that package might end up getting removed: https://github.com/STRML/JSXHint

**Comment by casesandberg** [comment]
Ah, well there you go
