### ISSUE TITLE
Fix Custom Rule in Tests

### ISSUE THREAD

**Issue by casesandberg** [AtomLinter/linter-jscs#162]
"the custom rule section is broken due to what appears to be the custom rule not being loaded"

https://github.com/AtomLinter/linter-jscs/pull/161

**Comment by Arcanemagus** [comment]
I've completely disabled that test in #224 as the rule needs a complete re-write to work with `jscs@^3.0.0`.

**Comment by Arcanemagus** [comment]
Marking this as closed, all JSCS development has [stopped](http://eslint.org/blog/2016/07/jscs-end-of-life) so there isn't much point in spending the effort on this when users should be moving to ESLint.
