### ISSUE TITLE
Error: Column start (7) greater than line length (5)

### ISSUE THREAD

**Issue by ChrisCinelli** [AtomLinter/linter-jscs#167]
I am getting a ton of these:

    Error: Column start (7) greater than line length (5)
        at Object.rangeFromLineNumber (/Users/rainehoover/.atom/packages/linter-jscs/node_modules/atom-linter/lib/helpers.js:173:11)
        at /Users/rainehoover/.atom/packages/linter-jscs/src/linter-jscs.js:137:33
        ...

It seems related with: https://github.com/AtomLinter/linter-eslint/issues/322

**Comment by Arcanemagus** [comment]
It has nothing to do with that, other than the same helper library complaining about being fed invalid data :wink:.

Do you have a file that consistently shows this error that you can share? And if you enable forcing parsing with ESNext in the options do you still see this?

**Comment by eiszfuchs** [comment]
I encounter the same problem, and was able to strip down a file I was working on to reproduce the error. It does not matter whether `Esnext` is checked or not.

Try changing `$day.html('');` to `$day.html('");` and hit save.

```js
$(function () {
    var resetDay = function () {
        var $day = $(this);

        $day.removeClass("loading today error no-offer");
        $day.html('');

        var today = moment().format(dateFormat);
        $day.toggleClass("today", today === $day.attr("data-date"));
        $day.toggleClass("selected", -1 < $.inArray(getRequestIdentifier($day),
            $.map(ticketSelection, function (d) { return d.day; })));
    };
});
```

**Comment by sebastianrosik** [comment]
I have the same problem in Atom 1.4.0 with linter-jscs 3.4.1. Any wrong syntax will throw this error: `foo('bar")`. I've tried to set the option "Display errors as" to "jscs Error" or "error", but nothing changed.

**Comment by workmanw** [comment]
:+1: I have the same problem. Ditto everything @sebastianrosik said is true for me.

**Comment by bob-v-t** [comment]
Same here

**Comment by casesandberg** [comment]
@arcanemagus are you able to reproduce this? I cant seem to be able to

**Comment by Arcanemagus** [comment]
Testing now.

**Comment by Arcanemagus** [comment]
I'm able to reproduce this with the "google" preset (Watch out, some other presets force enabling esnext).

_However_, when I enable Esnext (which switches to the `babel-jscs` parser) the error goes away. Verifying this takes ~20 min to go through all the calls, but I'm ~90% certain this is [this issue](https://github.com/jscs-dev/node-jscs/issues/2083) which is caused by a bug in `esprima`.

@eiszfuchs Since you say you see this whether or not "Esnext" is selected can you put a breakpoint [here](https://github.com/AtomLinter/linter-jscs/blob/v3.4.1/src/linter-jscs.js#L123) and see whether your `_this2.jscs._esprima` object looks like the top or bottom of these two:
![image](https://cloud.githubusercontent.com/assets/427137/12567760/ee692620-c375-11e5-8c45-39e3899a5e0a.png)

**Comment by workmanw** [comment]
@Arcanemagus Trying to help out here, I've never debugged Atom so I don't really know how to be helpful.

I tried turning on Esnext. Assuming I did it right, it still errors with Esnext. The stack trace seems exactly the same.

--------

**Settings:**
![image](https://cloud.githubusercontent.com/assets/825487/12571020/efa9e7e2-c3aa-11e5-8bbf-1c26adc0c97b.png)

------

**Stack:**
```
Error: Column start (85) greater than line length (84)
    at Object.rangeFromLineNumber (/Users/wesley/.atom/packages/linter-jscs/node_modules/atom-linter/lib/helpers.js:173:11)
    at /Users/wesley/.atom/packages/linter-jscs/src/linter-jscs.js:137:33
    at Array.map (native)
    at Object.lint (/Users/wesley/.atom/packages/linter-jscs/src/linter-jscs.js:134:39)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/wesley/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/wesley/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/wesley/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/wesley/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/wesley/.atom/packages/linter/lib/editor-linter.js:80:22
    at /Users/wesley/.atom/packages/linter/lib/helpers.coffee:23:18
```

----

**Breakpoint:**
![image](https://cloud.githubusercontent.com/assets/825487/12571100/94092514-c3ab-11e5-95db-c34ea2ae88c6.png)

**Comment by Arcanemagus** [comment]
That's just bizarre, @workmanw it looks like your settings are getting ignored and it is loading the `esprima` parser even though you have Esnext checked, can you file a new issue where we can debug that?

As for this issue, is your code something that can be shared? If so a gist with it would be nice to look over to see if it's the same bug as what I believe it to be.

**Comment by ChrisCinelli** [comment]
I definitely I was having problem with the google preset.
It is in an open source project and I would prefer that it keeps that setting.

**Comment by Arcanemagus** [comment]
@ChrisCinelli If you can point me to the file you were seeing this on I can verify if it's the same `esprima` parser bug most of the rest of these have turned out to be. You _should_ be able to just check the "Esnext" option to use the `babel-jscs` parser instead but keep the same `google` preset you are currently using, that is unless you are hitting the same issue as @workmanw where it isn't switching the parser for some reason.

**Comment by eiszfuchs** [comment]
@Arcanemagus
It looks like the bottom of the two (the one with `2.7.1`), no matter if I enable the setting or don't.

**Comment by workmanw** [comment]
@Arcanemagus Yeap, done. #168 . One other thing to mention, when I did add `"esnext": true` to my `.jscsrc` it did fix this issue. So that does seem to confirm your thinking regarding `esprima`. Thanks a lot for the support! :beers:

**Comment by eiszfuchs** [comment]
@workmanw Oh. Can confirm that setting the option in `.jscsrc` is working. Thanks! :beers:

**Comment by ChrisCinelli** [comment]
Is there a way to force `"esnext": true` without having to change `.jscsrc` ?

**Comment by workmanw** [comment]
@ChrisCinelli I'm not positive, but I believe that's the purpose of the setting. See: https://cloud.githubusercontent.com/assets/825487/12571020/efa9e7e2-c3aa-11e5-8bbf-1c26adc0c97b.png

But it seems like there might currently be an issue with that (#168).

**Comment by ChrisCinelli** [comment]
After I turned on ESNext option this error disappeared. 
I still see other errors popping up... Also a few time the editor become completely unresponsive and I had to quit it
Next time it happens I will find an issue with details.

**Comment by casesandberg** [comment]
https://github.com/AtomLinter/linter-jscs/issues/168 has been resolved, so setting ESNext in settings will force it everywhere.
