### ISSUE TITLE
Lint notices pop up as Atom errors

### ISSUE THREAD

**Issue by piotr-cz** [AtomLinter/linter-jscs#170]
Since recent update (not sure if _linter_ or _linter-jscs_) errors and warnings show on panel on the bottom and pop up as Atom uncatched error alerts with an error stack, as seen on attached screenshot.

![jscs-err](https://cloud.githubusercontent.com/assets/612953/12646195/dc4d6d06-c5ce-11e5-8491-55cf909abcf6.png)

which in this in this case referencing lines
```js
  if (colStart > lineLength) {
    throw new Error(`Column start (${ colStart }) greater than line length (${ lineLength })`);
  }
```

With the linter setting _Lint As You Type_ it's really hard to code.

___
Update: Disabling and enabling linter-jscs plugin resolves problem until next Atom start

**Comment by Arcanemagus** [comment]
That's actually an error, hence why it's showing as one :wink:.

There have been several issues with `jscs` lately that have been causing this, are you able to share a file that reproduces this so we can verify which one it is?

**Comment by piotr-cz** [comment]
You are right, it's not a jscs validation error that triggers this. I wasn't always able to trigger it for indentation, but always for file with such content:

```js
function Test() {
    console.log('hello);
}
```

![atom-problem](https://cloud.githubusercontent.com/assets/612953/12657948/43debede-c606-11e5-928f-50feff970e13.png)

**Comment by piotr-cz** [comment]
Alright, this https://github.com/AtomLinter/linter-jscs/commit/315117eae8912bdb0084074e2249816237afd12b fixes it.

**Comment by Arcanemagus** [comment]
Your second block shouldn't have triggered it, your first block is actually https://github.com/jquery/esprima/issues/1457 at it's root, which is what that commit works around.

**Comment by piotr-cz** [comment]
Thank you!
