### ISSUE TITLE
Add option to fix a specific lint error

### ISSUE THREAD

**Issue by ChrisCinelli** [AtomLinter/linter-jscs#173]
The fix on save, sometimes does too much cleaning. I may not want to change a whole file especially in older projects. It would be useful to have the option to autofix one line or the selected lines of code.

**Comment by casesandberg** [comment]
Ah, this is a great idea. Would be great to have this on the right click menu when you have a section made.

**Comment by Arcanemagus** [comment]
Does `jscs` suggest fixes in it's results, or does it _only_ support calling a fix method? If it suggests fixes in the results then it's a perfect fit for https://github.com/atom-community/linter/issues/1049 (although that isn't implemented yet...).

**Comment by Arcanemagus** [comment]
Marking this as closed, all JSCS development has [stopped](http://eslint.org/blog/2016/07/jscs-end-of-life) so this will never be fixed. Either downgrade to the [JSCS v2 version](https://github.com/AtomLinter/linter-jscs/releases/tag/v3.5.0) or preferably move to ESlint.

JSCS only ever supported the _global_ fix option, you would need a more advanced linter like ESlint to get per-message fixes anyway.
