### ISSUE TITLE
Recent changes to config merging leaves no way remove preset

### ISSUE THREAD

**Issue by workmanw** [AtomLinter/linter-jscs#177]
Recent changes made to the JSCS config merging strategy (960d04c9) leaves users without a way to not use a preset. `"preset": null` and `"preset": undefined` are not valid options for .jscsrc configuration. 

I proposed a new "preset" option being added to the package settings drop down for "\<none\>".

**Comment by joshmadewell** [comment]
+1

**Comment by cangoektas** [comment]
+1

Not only that, it also completely ignores my .jscsrc file (absolute path in project root) and just uses the airbnb preset. Only way to get around this for me is currently going back to c3699f009ab65b2b66c7dbb5157884dbeb15001a

**Comment by joshmadewell** [comment]
@cangoektas 

If you look at the PR: #178 you can see the code needed to get around this. It's actually an extremely simple change. You can just make the change locally until it gets merged in.

**Comment by Arcanemagus** [comment]
I'll be meeting that and releasing it as soon as I get to a computer BTW, unless @casesandberg beats me to it :wink:.

**Comment by cangoektas** [comment]
@joshmadewell Perfect, thanks for the hint!

**Comment by workmanw** [comment]
:D Thanks for the support @joshmadewell, @cangoektas and @Arcanemagus .

@Arcanemagus -- I know it's an entirely separate issue and generally not good to cross the streams, but if you're planning to cut a new release I think #175 (fixed by #176) is also worth considering. It's unfortunately a blocker for us to even use the linter-jscs package. 

Thanks again.

**Comment by Arcanemagus** [comment]
Fix published in v3.4.5, please reopen if this is still an issue!

**Comment by workmanw** [comment]
:+1: I've confirmed on my end that the upgrade did fix it. Cheers.
