### ISSUE TITLE
Some rules are auto-enabled as of 3.4.4

### ISSUE THREAD

**Issue by globexdesigns** [AtomLinter/linter-jscs#179]
After the 3.4.4 linter-jscs upgrade, I've started getting the following three rule errors in all my files: "requireTrailingComma", "validateLineBreaks", "disallowSpaceAfterObjectKeys".

To fix this, I've had to go into my `.jscsrc` file and set those rules explicitly to `false` (whereas before they were simply not present in the file at all).

These errors do not appear when running JSCS via the CLI, and they do not appear when using linter-jscs before version 3.4.4, so something must have changed to cause this issue. It's as if linter-jscs is setting some rules to be enabled by default.

This is still an issue in 3.4.5

*EDIT* Actually this isn't limited to the 3 rules mentioned. A lot of other rules are showings warnings as well.

**Comment by kabalage** [comment]
+1 
3.4.5 here and I have the same problem.

**Comment by NKjoep** [comment]
I agree. Same problem with osx and latest version. Please fix it! :D

**Comment by casesandberg** [comment]
Can you do me a favour and comment out a line in the package and restart atom to see if this fixes it? I can't seem to reproduce it. 

If you edit the package here: `~/.atom/packages/linter-jscs/src/linter-jscs.js` and comment out line 115 `this.jscs.registerDefaultRules();` and restart atom. Is it still thorwing rules?

**Comment by Arcanemagus** [comment]
Can you please move back to v3.4.5 and verify that your `Preset` configuration option is set to `<none>`? Otherwise you will be merging settings from a preset into your configuration.

**Comment by swaj** [comment]
Swapping the global preset to "<none>" did fix the problem for me.

**Comment by gregtyler** [comment]
I think this issue has been mislabelled. I believe the issue is that my .jscsrc file isn't being picked up by linter-jscs, so the preset is being applied. This gives the impression of extra rules being applied, but it's actually a different ruleset that happens to have some crossovers.

Easiest evidence for me is switching between "airbnb" and "yandex" in the presets to see the indent validation change from "2 spaces" to "4 spaces" (when my .jscsrc file doesn't give any specification).

This happens when the JavaScript file is in the same folder as .jscsrc

**Comment by rjmunro** [comment]
I found switching the prefix to `<none>` worked as well.

**Comment by gregtyler** [comment]
@rjmunro Switching to `<none>` works for me too. Good call.

**Comment by Arcanemagus** [comment]
@rjmunro `<none>` is not currently equivalent to that, but it probably should be...

**Comment by raoel** [comment]
When I installed linter-jscs 1 days ago this issue immediately popped up. Could it be that the default setting for the preset is something else than <none>?

**Comment by Arcanemagus** [comment]
The default is `airbnb` (as you could see by glancing at your settings...).

**Comment by globexdesigns** [comment]
How do you set the preset to none? This is what I see when I try to change it:

![screen shot 2016-02-10 at 12 22 59 pm 1](https://cloud.githubusercontent.com/assets/226640/12960628/158c8c56-cff1-11e5-8cb4-6d9d9fa6acc1.png)

**Comment by Arcanemagus** [comment]
@globexdesigns You need to update to v3.4.5.

**Comment by globexdesigns** [comment]
I was. But had to restart Atom too. All good now. Thanks.

**Comment by Arcanemagus** [comment]
Ah, `settings-view` must not update when a package updates.

**Comment by epsitec** [comment]
Editing manually my settings to:
```
  "linter-jscs":
    esnext: true
    fixOnSave: true
    harmony: true
    preset: "<none>"
    verbose: true
```
does revert the displayed _preset_ to `airbnb` which is not what I want (it worked in v3.4.6, is now broken in v3.4.8).

**Comment by Arcanemagus** [comment]
@epsitec As that config value is an `enum`, I would expect Atom to ignore invalid input...

v3.4.8 should have no need of the `<none>` option, as it properly only uses the preset if a configuration can't be found.
