### ISSUE TITLE
Add option to disable validation if there is no .jscsrc file

### ISSUE THREAD

**Issue by MoOx** [AtomLinter/linter-jscs#18]
I work on a lot of different projects. They don't have the same coding convention & I mainly use jscs for personal project so it will be cool to have a way to enable jscs only if there is a reason (a jscsrc file ?)
Is it doable ?

**Comment by iam4x** [comment]
Fixed with https://github.com/AtomLinter/linter-jscs/commit/ff783059af77e79338354e88e95e7a05b67ca3dc it will be present in next release
