### ISSUE TITLE
requireTrailingCommma defaults to true

### ISSUE THREAD

**Issue by axit-rasmus** [AtomLinter/linter-jscs#182]
With the below setup atom keeps complaining about a missing/unexpected comma.
With fix-on-save it alternates between adding and removing the comma. Linting with jscs as part of the build correctly disallows the dangling comma.

According to the plugin, the rule ```requireTrailingComma``` is active, while according to the dotfile and the separate linter it is not.

To repro:

foo.js
```
const a = {
  b: null
}
```

.jscs.yaml
```
disallowTrailingComma: true
```

**Comment by Arcanemagus** [comment]
Can you please update to v3.4.5 and set the preset choice to `<none>`? I'm betting your settings are being merged with a preset.

**Comment by erikdonohoo** [comment]
This does fix the issue, but it previously didn't merge settings with presets, even when presets were selected.  Thanks for the info for the fix, I had this issue too.

**Comment by Arcanemagus** [comment]
This was added in https://github.com/AtomLinter/linter-jscs/issues/168 as part of getting the `ESNext` option to actually work.
