### ISSUE TITLE
Could I use this if I installed "linter-eslint"?

### ISSUE THREAD

**Issue by thearabbit** [AtomLinter/linter-jscs#188]
Could I use this if I installed "linter-eslint"?

**Comment by casesandberg** [comment]
Yes, you totally can! You may have to tweak some of your rules in either `.eslintrc` or `.jscsrc` so that they don't cause conflicts. There are some rules that the each turn on by default that might contradict eachother,

**Comment by Arcanemagus** [comment]
You could also set both of these packages to only run when there is a configuration present, then only ones that you have configured will run.

**Comment by thearabbit** [comment]
Thanks for your reply.
