### ISSUE TITLE
Doesn't work (Win 8.1, Atom 0.123.0, Linter 0.5.14, Linter Jscs 1.4.9)

### ISSUE THREAD

**Issue by MartinMa** [AtomLinter/linter-jscs#19]
I'm not sure if it is my fault somehow, but it just doesnt' work.

I tried the following code snipped, but I just don't get any errors:
```javascript
var bla = {
  "blubb": 4 ,
  "yada": 2
  ,"hey": 3
}
```

My setup is
Win **8.1**
Atom **0.123.0**
Linter **0.5.14**
Linter Jscs **1.4.9**

Other linters like linter-jshint and linter-eslint do work.

**edit** The developer console does print `activate linter-jscs`

**Comment by iam4x** [comment]
@vtintillier I have no windows computer ready to use here, with the updated versions of `jscs` is there's still the bug?

**Comment by vtintillier** [comment]
It works fine now, thanks!
