### ISSUE TITLE
Settings: preset

### ISSUE THREAD

**Issue by lnfnunes** [AtomLinter/linter-jscs#190]
### Version
3.4.6

### Issue
In the settings, the "Preset" option definition says:
*Preset option is ignored if a config file is found for the linter.*

But it looks like if I have a local .jscsrc file, instead of totally ignoring the preset option it's extending it and only overwriting declared rules.

Test case:
 - I've set "google" preset in my settings
 - My local .jscsrc file **don't** have the declaration *"disallowSpaceAfterObjectKeys"*.
 - The linter is warning me that it has an error!

So,
my suggestion is to change the Preset description or fix the behavior.

**Comment by casesandberg** [comment]
It seems like a lot of people are having issues with this new behaviour and I dont know that I like it so I will think on it a little more but probably revert it.

**Comment by lnfnunes** [comment]
I realized this behavior when my Atom catches errors on a file and on my team partner editor (Brackets and Webstorm) didn't. So I check if the build linting was catching it and it didn't too!

My point is: the way it is can cause this type of misunderstood on a team workflow.
IMHO, the current behavior is fine for alone working but on a team, it's expected the project rule is the one versioned configuration file (.jscsrc) instead of local editor settings. What do you think ? 

Thanks

**Comment by casesandberg** [comment]
Yeah, I agree with you-- I am going to switch it back!

**Comment by lnfnunes** [comment]
:+1:

**Comment by santagu** [comment]
The same happens to me with another errors. I would be grateful if you fix it! :)

**Comment by santagu** [comment]
well, I'm a bit stupid... :) if you put <none> in presets works fine with me and only pick up my .jscsrc options.
