### ISSUE TITLE
fix before save

### ISSUE THREAD

**Issue by dwelle** [AtomLinter/linter-jscs#194]
Current _fix on save_ forces the user to save 2x in order for the file to get saved (first save fixes the file, second one saves the fixed file). The problem this creates is you're sometimes not sure if you've saved the file because in tab bar it always shows as unsaved after the first save, which can be annoying (extra compile which can take time; doubles the disk writes...).

I was about to make a PR that adds `fixBeforeSave` (via `onWillSave()`), but then I wondered - why is this not the default? Is there any use case the user would like to retain the _save file 2x_?

EDIT: apart from if the fix is done _before_ save, there's some weird visual bug where the file loses grammar styling for a split of a second (resulting in a flash). Not sure what's going on there (how that differs from fix _after_ save).

**Comment by Arcanemagus** [comment]
If the user has Fix On Save enabled, I would imagine they are expecting what you get from hooking into `onWillSave()`. I'm also not sure why this was setup like this... that was implemented back when `linter` supported "buffer modifying linters", but for some reason the maintainers of this package at the time never bothered to actually utilize that functionality (leading to some conflicts...). As no `linter-*` plugins were using that it was removed from `linter`, but this is still using `onDidSave()` for some reason.
