### ISSUE TITLE
Uncaught Error: Parse error on line 17:...d\" 

### ISSUE THREAD

**Issue by tr222cj** [AtomLinter/linter-jscs#195]
[Enter steps to reproduce below:]

1. Sorry but I can't actually tell you how this happened. I was editing files just fine and suddenly this error just started spamming my screen. Perhaps i happened after a git push but I can't say that for sure. Error appears each time I try to save a file.

**Atom Version**: 1.5.3
**System**: Microsoft Windows 10 Home
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v3.4.6

### Stack Trace

Uncaught Error: Parse error on line 17:
...d\"

**Comment by Arcanemagus** [comment]
Is that the entire stack trace?

**Comment by Arcanemagus** [comment]
Do you have an example file that triggers this?

**Comment by tr222cj** [comment]
I tried to reproduce the steps I took yesterday but I was not able to.
Between the time I got the error and yesterday I have reinstalled Atom so
perhaps it was some corrupted config-files. I vote to just close the Issue
with Unable to reproduce :)

2016-02-23 7:20 GMT+01:00 Landon Abney <notifications@github.com>:

**Comment by Arcanemagus** [comment]
Works for me :stuck_out_tongue:

If you are ever able to reproduce this please respond back here, or file a new issue.
