### ISSUE TITLE
Airbnb is overriding my local config on 'Fix on Save'

### ISSUE THREAD

**Issue by HauptmannEck** [AtomLinter/linter-jscs#197]
### Version
3.4.7
### Issue
Using the rule: 
disallowTrailingComma
When 'Fix on Save' and 'Only Config' is selected with a preset of 'airbnb', instead on removing the trailing commas, it adds them. Then errors that there are trailing spaces.

If I switch to 'google' as a preset then they problem goes away.

**Comment by HauptmannEck** [comment]
Is there supposed to be a 'none' option? I cannot see it, even after restarting Atom.

**Comment by dwelle** [comment]
regression from https://github.com/AtomLinter/linter-jscs/commit/f13fc7797840e5f5c838c7128df0e1e5fb2f82b1

**Comment by Arcanemagus** [comment]
Fix published in v3.4.8, can you verify @HauptmannEck?

**Comment by HauptmannEck** [comment]
Verified the fix, all is well.

**Comment by Arcanemagus** [comment]
Glad to hear it :wink:.

**Comment by dwelle** [comment]
Not fixed for me, but I'm having some issues with atom cache so I'm not 100% positive. But reading the [code](https://github.com/AtomLinter/linter-jscs/blob/master/src/linter-jscs.js#L219), it's not fixed yet. It still checks for `<none>` preset which is now missing from the list.

/cc @Arcanemagus @HauptmannEck

**Comment by Arcanemagus** [comment]
@casesandberg Looks like v3.4.7 didn't fully take into account the places presets are looked at, mind taking a look?

**Comment by zoltanradics** [comment]
When linter-jscs is enabled and my .jscsrc file is located in my project folder, linter-jscs is changing between the (probably) airbnb and my preset on each save. Which means i save my file once and it fixes with my preset and if i save again, it fixes with (probably) Airbnb preset. My package config is: Config file path: (empty), Esnext: false, Fix on save: true, Only config: true.

**Comment by epsitec** [comment]
Here is my configuration, manually edited to have `preset` set to `<none>`:

```
  "linter-jscs":
    esnext: true
    fixOnSave: true
    harmony: true
    preset: "<none>"
    verbose: true
```

However, in Atom (with v3.4.8), I see this:

![airbnb-default](https://cloud.githubusercontent.com/assets/3872435/13735803/2e73c8a2-e9ae-11e5-902e-033c8e416d6e.png)

and the _fix on save_ feature still breaks my layout.

**Comment by epsitec** [comment]
Please add the `<none>` option back in at line 19:

```javascript
  static config = {
    preset: {
      title: 'Preset',
      description: 'Preset option is ignored if a config file is found for the linter.',
      type: 'string',
      default: 'airbnb',
      enum: ['<none>', 'airbnb', 'crockford', 'google', 'grunt', 'idiomatic', 'jquery', 'mdcs', 'node-style-guide', 'wikimedia', 'wordpress', 'yandex'],
    },
```

**Comment by Arcanemagus** [comment]
@epsitec There should be no need of that setting, the fact that Fix on Save wasn't properly updated to not need it doesn't mean it should be added back...

As it looks like @casesandberg hasn't had time to look into this I'll see if I can as it seems nobody has put up a PR fixing this.

**Comment by epsitec** [comment]
@Arcanemagus that would be nice. I have no idea how you would debug the plugin in atom while it is running, so I'll happily let somebody else who is more comfortable with the idea propose a PR ;-)

**Comment by Arcanemagus** [comment]
Okay, real fix is published in v3.4.9. Please verify that it's working properly for you.

**Comment by zoltanradics** [comment]
Now It's seems to be working for me. Thanks!

**Comment by epsitec** [comment]
OK for me too.
