### ISSUE TITLE
Fix on save doesn't work correctly

### ISSUE THREAD

**Issue by syerad** [AtomLinter/linter-jscs#198]
### Version
3.4.8

### Issue
If the option `Fix on save` is enabled there is a wrong behaviour.
If the rule `requireSpacesInsideParentheses` is enabled and a file is beeing saved
the linter reverses the rule on every save action.
For example: (with spaces)
```
            $( '#history' ).val( maxValue );
```

After first save:
```
            $('#history').val(maxValue);
```
The spaces are gone

After another save:
```
            $( '#history' ).val( maxValue );
```
The spaces are there...

If there are lines with spaces and without spaces in a single file the spaces will
be removed respectively will be added on each save

**Comment by syerad** [comment]
Maybe it is the same Issue like #197

**Comment by syerad** [comment]
I will try to use a different preset than airbnb and test if the wrong behavior remains

**Comment by syerad** [comment]
With some presets the problem occurs, with others it doesn't occurs. I think the problem is the rule `requireSpacesInsideParentheses`.

**Comment by Arcanemagus** [comment]
This definitely looks like it's the same issue as #197, I'll close this for now and if it's still a problem when that gets fixed we can re-open this.
