### ISSUE TITLE
excludeFiles not being used

### ISSUE THREAD

**Issue by aaronbdixon** [AtomLinter/linter-jscs#20]
I have a .jscsrc file that contains an excludeFiles array. The items in that array are not being excluded. When I open files in the excluded directories the file is lighting up with issues. I'm excluding external libraries. I know the patterns are correct because they work with gulp-jscs.

**Comment by erikdonohoo** [comment]
:+1: 
This needs to be implemented badly

**Comment by iam4x** [comment]
It's looking for files in the path of the executable, I will try to implement a custom method to remove linter when the file match one in the excludeFiles array.

**Comment by erikdonohoo** [comment]
@iam4x That would be awesome

**Comment by diegoaguilar** [comment]
Won't this work for glob patterns?
