### ISSUE TITLE
Can't get linting to work

### ISSUE THREAD

**Issue by jkrenge** [AtomLinter/linter-jscs#207]
### Version
- Atom `1.6.0`
- linter `1.11.4`
- linter-jscs `3.4.10`
- linter-jshint `2.0.3`

### Issue
So `linter` and `linter-jshint` are working fine, as you can see from the screenshot:

<img width="394" alt="screen shot 2016-03-27 at 17 15 02" src="https://cloud.githubusercontent.com/assets/625618/14066017/7b79a9f0-f43f-11e5-842f-4cf4ed0c711c.png">

However, I can't get `linter-jscs` to work, there's no output, as you can see above. It should highlight the missing ` ` after `if`.

My `config.cson` shows basically default settings:

```
  "linter-jscs":
    displayAs: "warning"
  "linter-jshint": {}
```

I also tried auto-generating the `.jscsrc` config file and referencing it:

```
  "linter-jscs":
    configPath: "./.jscsrc"
```

But this didn't help either.

---

I am relatively sure I am just making a really stupid mistake. :-)

**Comment by jkrenge** [comment]
I did something, don't know what, but now it's okay. Maybe it was [language-javascript-semantic](https://atom.io/packages/language-javascript-semantic). Sorry for bothering you guys.

**Comment by casesandberg** [comment]
Nice 🙌
