### ISSUE TITLE
Fix file from command palette instead of on save

### ISSUE THREAD

**Issue by niekert** [AtomLinter/linter-jscs#211]
### Version
linter-jscs: 3.4.10
Atom: 1.6.2

### Issue
I was wondering if it was possible to fix the file from the command palette, rather than having to enable the fix file on save feature? I don't want to fix my file every time I press save, but would like to be able to do it from the command palette. 

Unfortunately I can't find any information on this. I tried the [jscs-fixer](https://atom.io/packages/jscs-fixer) package, but it causes a lot of errors and does not fix the file for me.

**Comment by Arcanemagus** [comment]
It doesn't look like this package currently registers any commands, if you want to put together a PR implementing this I'd be happy to merge it.

You can look at how `linter-eslint` does this [here](https://github.com/AtomLinter/linter-eslint/blob/v7.1.3/src/main.js#L79) to get you started.

**Comment by niekert** [comment]
Awesome! Here's the PR:

#212

**Comment by Arcanemagus** [comment]
Oh this is just plain _bizarre_, this is the second issue I've commented on today where the initial post is completely blanked :open_mouth:.

**Comment by niekert** [comment]
Hmm, very strange indeed 🤔. I did include a description when I created the issue earlier today, assumed you removed it

**Comment by Arcanemagus** [comment]
I didn't intentionally, it looks like something is broken though.

**Comment by Arcanemagus** [comment]
Looks like it was a bug on GitHub's side when the label's were assigned: https://status.github.com/messages
