### ISSUE TITLE
Unsupported rule error in first line of document.

### ISSUE THREAD

**Issue by pinzonjulian** [AtomLinter/linter-jscs#214]
### Version
3.5.5

### Issue
AtomLinter prompts me with an error that doesn't exist. It appears on the first line of the document no matter what code is written on it. Even if its a comment. 
<img width="1552" alt="screen shot 2016-04-10 at 11 31 10 am" src="https://cloud.githubusercontent.com/assets/10928518/14411507/bf1cca18-ff0f-11e5-80c4-f06ab6b21cfd.png">

I created some blank space above the error and it migrates lines, as if it were attached to the first line of the document. The error still says it's in line 1 when it's actually in line two. 

<img width="1552" alt="screen shot 2016-04-10 at 11 28 36 am" src="https://cloud.githubusercontent.com/assets/10928518/14411499/96cd5c9e-ff0f-11e5-8c87-5f1c8f4bba5d.png">

Below is my .jscsrc code. It's from John Papa's pluralsight course on Gulp.

`{
    "excludeFiles": ["node_modules/**", "bower_components/**"],

    "requireCurlyBraces": [
        "if",
        "else",
        "for",
        "while",
        "do",
        "try",
        "catch"
    ],
    "requireOperatorBeforeLineBreak": true,
    "requireCamelCaseOrUpperCaseIdentifiers": true,
    "maximumLineLength": {
      "value": 100,
      "allowComments": true,
      "allowRegex": true
    },
    "validateIndentation": 4,
    "validateQuoteMarks": "'",

    "disallowMultipleLineStrings": true,
    "disallowMixedSpacesAndTabs": true,
    "disallowTrailingWhitespace": true,
    "disallowSpaceAfterPrefixUnaryOperators": true,
    "disallowMultipleVarDecl": null,

    "requireSpaceAfterKeywords": [
      "if",
      "else",
      "for",
      "while",
      "do",
      "switch",
      "return",
      "try",
      "catch"
    ],
    "requireSpaceBeforeBinaryOperators": [
        "=", "+=", "-=", "*=", "/=", "%=", "<<=", ">>=", ">>>=",
        "&=", "|=", "^=", "+=",

        "+", "-", "*", "/", "%", "<<", ">>", ">>>", "&",
        "|", "^", "&&", "||", "===", "==", ">=",
        "<=", "<", ">", "!=", "!=="
    ],
    "requireSpaceAfterBinaryOperators": true,
    "requireSpacesInConditionalExpression": true,
    "requireSpaceBeforeBlockStatements": true,
    "requireLineFeedAtFileEnd": true,
    "disallowSpacesInsideObjectBrackets": "all",
    "disallowSpacesInsideArrayBrackets": "all",
    "disallowSpacesInsideParentheses": true,

    "validateJSDoc": {
        "checkParamNames": true,
        "requireParamTypes": true
    },

    "disallowMultipleLineBreaks": true,

    "disallowCommaBeforeLineBreak": null,
    "disallowDanglingUnderscores": null,
    "disallowEmptyBlocks": null,
    "disallowMultipleLineStrings": null,
    "disallowTrailingComma": null,
    "requireCommaBeforeLineBreak": null,
    "requireDotNotation": null,
    "requireMultipleVarDecl": null,
    "requireParenthesesAroundIIFE": true
}
`

**Comment by Arcanemagus** [comment]
As the error is pretty clearly telling you, `validateJSDoc` isn't a valid `jscs` rule... remove that line and it should start working properly (or tell you of any further errors in your configuration). If that was a valid rule then [this link](http://jscs.info/rule/validateJSDoc) wouldn't be a 404, and it would be listed [here](http://jscs.info/rules).

Maybe that "rule" is coming from an extension you didn't install?
