### ISSUE TITLE
"Fix on save" runs even when the linter is toggled off.

### ISSUE THREAD

**Issue by RobertWHurst** [AtomLinter/linter-jscs#223]
### Version
3.5.0

### Issue
The "fix on save" runs even when linter has been disabled. This can be annoying when working on vendored/3rd party code one does not wish to be linted or formanted.

**Comment by Arcanemagus** [comment]
What do you mean by "disabled"? It's literally impossible for it to run when the package is disabled unless there is a _serious_ bug in your Atom install.

**Comment by RobertWHurst** [comment]
Not sure. Seeing as I haven't seen this issue for a while I'll close it. That said, when I reported this, I used the error dialog from within Atom. Atom picked this package out directly. I'm not sure how it was running when the extension was disabled, and I will admit I didn't do any digging. I'm going to assume was an anomaly or has been fixed.

**Comment by Arcanemagus** [comment]
Bizarre, thanks for reporting back though!

**Comment by RobertWHurst** [comment]
@Arcanemagus 🍻
