### ISSUE TITLE
Add rule name to error message

### ISSUE THREAD

**Issue by tbusser** [AtomLinter/linter-jscs#23]
I am not sure if this is within the realm of possibilities of this plugin but it would be very helpful if the error would include the name of the rule that generated the error. The JSHint linter does this, it shows W-numbers for each error, and it is a big help when trying to figure out which rule you broke. 
![jshint-errors](https://cloud.githubusercontent.com/assets/5519027/4474236/47f52cd2-495d-11e4-85d8-5621e4a97601.jpg)

I am trying to track down why I am getting the errors displayed in the image below and I have no clue where to start looking. I have the rule `requireAlignedObjectValues` set to `ignoreFunction` but some other rule is complaining about the illegal use of spaces after a key.
![lint-errors](https://cloud.githubusercontent.com/assets/5519027/4474210/fd4e5870-495c-11e4-949a-54490f076547.jpg)
In addition there is the message about the expected indentation of 3 characters which has me puzzled. I have no way of knowing which rules are generating these messages and thus I can't fix my rules to suit my style of coding.

**Comment by iam4x** [comment]
@tbusser Should be fixed with 1.6.0 release
