### ISSUE TITLE
Important jscs issue!

### ISSUE THREAD

**Issue by Exelord** [AtomLinter/linter-jscs#240]
### Version
4.0.0

### Issue
After upgrade to the latest version linter just stopped working due to:
![screen shot 2016-05-10 at 10 34 20](https://cloud.githubusercontent.com/assets/1469375/15140342/ee2591da-169a-11e6-91aa-ab0fb34c723d.png)

**Comment by ticktricktrack** [comment]
same here, with both jscs `2.9` and `3.0.3`

**Comment by electerious** [comment]
Please read the error and the jscs changelog and update your .jscsrc file as described. See #233, #232, #231, #230.

**Comment by Arcanemagus** [comment]
As @electerious said, the error message told you everything you needed to know: You are specifying the `esnext` and/or `verbose` options in your configuration, which have been removed in `jscs@3`. If you for some reason can't update to the latest version of `jscs` you can simply downgrade the plugin to one that integrates `jscs@2`.
