### ISSUE TITLE
Error parsing default values for function parameters 

### ISSUE THREAD

**Issue by cscleison** [AtomLinter/linter-jscs#242]
### Version
4.0.0

### Issue
It does not parse properly ES2015 functions with default values for its parameters.

### Message
Expected token value ":" but = found

### Code
const fn = (param=1) => console.log(param);

**Comment by Arcanemagus** [comment]
What configuration are you using?

**Comment by cscleison** [comment]
```
{
  "preset": "idiomatic",
  
  "maximumLineLength": 80,
  "validateLineBreaks": null,

  "disallowMultipleLineBreaks": true,
  "disallowSpaceBeforeSemicolon": true,

  "requireSpacesInsideParentheses": false,
  "requireSpacesInsideBrackets": false,
  "requireSpacesInsideObjectBrackets": false,
  "requireCurlyBraces": false,
  "requireSpaceAfterComma": false,
  "requireOperatorBeforeLineBreak": false,
  "requireCommaBeforeLineBreak": false,
  "disallowSpaceBeforeComma": false,
  "disallowSpaceBeforeBinaryOperators": false,
  "validateQuoteMarks": false,
  "validateCommentPosition": false
}
```

**Comment by Arcanemagus** [comment]
@cscleison I can't reproduce this using this package _or_ the CLI interface. Can you upload a zip file of the file you are seeing that on, and the relevant configuration?

For example, here is what I'm using to try to reproduce this: [linter-jscs_GH242.zip](https://github.com/AtomLinter/linter-jscs/files/260129/linter-jscs_GH242.zip)

**Comment by cscleison** [comment]
@Arcanemagus using your files I figured out the code this linter doesn't like:
`componentX = ({ value = []}) => {};`

it's a sintax for [react stateless components](https://medium.com/@joshblack/stateless-components-in-react-0-14-f9798f8b992d#.6cfeqmkpj)

**Comment by Arcanemagus** [comment]
Okay, this is definitely a `jscs` issue then, you'll need to file an issue over on [their issue tracker](https://github.com/jscs-dev/node-jscs/issues) about this, or downgrade to an older version and use something [like this](https://bl.ocks.org/hahahana/3d5fa343f850f4c7fdc3) to get it working.

Alternatively you can use `eslint`, which supports modular parsers and plugins and can easily support React projects.

**Comment by cscleison** [comment]
Thank you, @Arcanemagus !

**Comment by Arcanemagus** [comment]
Fyi, if you do decide to stay on `jscs` and go the older method route, you will need to run `apm install linter-jscs@3.5.0` to get the last version of this that worked with the JSCS v2 branch.
