### ISSUE TITLE
'use strict' throw maximumLineLength

### ISSUE THREAD

**Issue by Kikobeats** [AtomLinter/linter-jscs#251]
### Version

atom: 1.7.3
linter-jscs: 4.0.1
jscs: 3.0.3

### Issue

<img width="611" alt="screen shot 2016-05-17 at 10 56 23" src="https://cloud.githubusercontent.com/assets/2096101/15316592/0061a9a0-1c1e-11e6-9d44-90d6cfcaae32.png">

in all files that have `use strict` in the header declared 😐

**Comment by Arcanemagus** [comment]
Does `jscs` on the CLI show the same behavior? If not, can you provide a file that demonstrates this, as well as the relevant `.jscsrc`?

**Comment by Kikobeats** [comment]
hmmm strange:

````
❯ jscs index.js
maximumLineLength: Line must be at most 100 characters at index.js :
     1 |'use strict';
--------^
```

File rules:
````
```

**Comment by Arcanemagus** [comment]
Definitely something wrong with `jscs` then, can you file an issue over there referencing this so anyone finding this later can see the resolution?

**Comment by Kikobeats** [comment]
👍

**Comment by agarcian** [comment]
I am experiencing the same issue.   I have several files that are getting this error on the first line/first character of the file.

    maximumLineLength: Line must be at most 80 characters at ./client/app/shared/services/roles/roles.js :
         1 |import clone from 'lodash/clone';
    --------^

**Comment by Arcanemagus** [comment]
@agarcian It's a bug in JSCS, there's nothing that can be done about here in this project. It doesn't look like @Kikobeats filed an issue yet, if you want to file one [over there](https://github.com/jscs-dev/node-jscs/issues/new) that would be the first step in getting this fixed.
