### ISSUE TITLE
Unable to use "airbnb" preset

### ISSUE THREAD

**Issue by tbeseda** [AtomLinter/linter-jscs#26]
I can set my preference to `google`, `jquery`, etc. but `airbnb` does not work.

Linter with `google`:
![screen shot 2014-11-06 at 11 03 25 am](https://cloud.githubusercontent.com/assets/15697/4941010/d58e5e30-65df-11e4-9e2c-381e257a0df7.png)

Linter with `airbnb`:
![screen shot 2014-11-06 at 11 02 09 am](https://cloud.githubusercontent.com/assets/15697/4941015/da443eae-65df-11e4-992e-ea0c41af858e.png)

I would expect line 2 to be flagged (as [documented by](https://github.com/airbnb/javascript#strings) @airbnb), in addition to line 6.

Any ideas?  
Thanks.

**Comment by iam4x** [comment]
@tbeseda Should be fixed with next release, added the reference for all preset in a select.

**Comment by tbeseda** [comment]
Thanks @iam4x, I appreciate it!
