### ISSUE TITLE
Question about config file usage

### ISSUE THREAD

**Issue by adarrra** [AtomLinter/linter-jscs#260]
### Version
4.0.2

### Issue
Hi! I want to use removed yandex preset. So I copy it's rules to "yandex.json" file and fill "Config file path" field (in settings) as "/home/myuser/yandex.json"
But it doesn't work. How can I debug what am I doing wrong?

**Comment by Arcanemagus** [comment]
Why aren't you just putting the rules into a `.jscsrc` file in the project?

As for why what you are doing isn't working I'm not sure, can you open the Developer Tools, put a breakpoint [here](https://github.com/AtomLinter/linter-jscs/blob/v4.0.2/src/linter-jscs.js#L240) and see what is being loaded for the config?

**Comment by adarrra** [comment]
thanx for your advice!
I need this because team use old version of jscs in a project and in our .jscsrc we just use this preset. 
Maybe I should just freeze the version of atom linter package also.

I trying to debug but config just undefined, I went into configFile.load() but I didn't fully understand what happened there (content is undefined).

**Comment by Arcanemagus** [comment]
If your team isn't updating your best bet is probably to just stick to the older version of this package.

**Comment by adarrra** [comment]
ok, but interesting why not working my config file

**Comment by Arcanemagus** [comment]
This is still open to remind me (or anyone else...) to investigate this when they have a chance :wink:.

**Comment by adarrra** [comment]
Ok, I find out the problem was in file name. I change it to ".jscs.json" and everything works. Sorry for bothering!

**Comment by Arcanemagus** [comment]
Thanks for reporting back!
