### ISSUE TITLE
validateIndentation on switch statements fails if opening bracket is on new line

### ISSUE THREAD

**Issue by Tathanen** [AtomLinter/linter-jscs#261]
### Version
4.0.2

### Issue
I'm guessing this is a linter-jscs error, as it doesn't seem like this behavior makes sense in the spec.

If you have `validateIndentation` set to an integer (in my case `4`), it complains about switch statements where the opening curly bracket isn't on the opening line.  See:

Freaks out:
![Error](http://i.imgur.com/LeqWaI9.png)

Fine:
![Fine](http://i.imgur.com/8i0OlyJ.png)

I write my code Allman style and everything else is fine, just switch statements seem to be actin weird.

**Comment by Arcanemagus** [comment]
Does `jscs` on the CLI show the same messages? This seems like an issue with `jscs` and not the translation of its messages for the `linter` package, which is all this package does.

**Comment by Tathanen** [comment]
Yep you're right, the issue is present in the CLI.  Will open an issue on the actual JSCS repo.
