### ISSUE TITLE
linter-jscs not reading package.json

### ISSUE THREAD

**Issue by mrgamer** [AtomLinter/linter-jscs#28]
Using jscs with a node.js project, I find it quite handy to just write its configuration inside `package.json`.

It's a documented [feature here](http://jscs.info/overview.html#cli), and works just out of the box using `jscs` from command line.

What is breaking it is [that line](https://github.com/AtomLinter/linter-jscs/blob/master/lib/linter-jscs.coffee#L31)

I may pop in a simple PR (given my near-to-zero coffeescript skills) if you agree this feature should work exactly as `node-jscs` does

**Comment by adius** [comment]
+1

**Comment by iam4x** [comment]
Sorry for late answer @adius @mrgamer, it's now supported.
