### ISSUE TITLE
Expected token type "Punctuator" but "Identifier" found

### ISSUE THREAD

**Issue by purplecones** [AtomLinter/linter-jscs#282]
### Version
4.0.5

### Issue
I get the following error when using async / await 

![resolvers_js_ __users_mirzajoldic_projects_models-graphql_and_resolvers_js_ __users_mirzajoldic_projects_capfundr-app_and_does_not_support_async_methods_ _issue__2270_ _jscs-dev_node-jscs](https://cloud.githubusercontent.com/assets/136654/16808573/01306ac0-48eb-11e6-951b-1470893c3214.png)

according to this issue https://github.com/jscs-dev/node-jscs/issues/2270 , it was resolved

### Sample Code
```javascript
import shortid from 'shortid';

const rootResolvers = () => {
  return {
    Query: {
      async test(root, args, context) {
        return test;
      },
    },
  };
};

export default rootResolvers;
```

Is this the appropriate place to post this issue? If not, please direct me to where it should be posted. Thanks.

**Comment by Arcanemagus** [comment]
Do you run into the same message when you run `jscs@3.0.6` on the file from the CLI? `linter-jscs@4.0.5` includes that version, which should have the relevant commit, assuming that actually fixes your issue.

**Comment by purplecones** [comment]
Yes I do:

```
jscs resolvers.js -c airbnb.json
Expected token type "Punctuator" but "Identifier" found at resolvers.js :
     1 |import shortid from 'shortid';
--------^
     2 |
     3 |const rootResolvers = () => {


1 code style error found.
```

So it's seems to still be an issue with jscs ?

**Comment by purplecones** [comment]
FYI, see Issue https://github.com/cst/cst/issues/133 that fixes this

**Comment by Arcanemagus** [comment]
Marking this as closed since it's a JSCS issue, as soon as a new version is released we should get a PR updating to it 😉.
