### ISSUE TITLE
linter-jscs blocks my editor's interactivity on save

### ISSUE THREAD

**Issue by wonderbeyond** [AtomLinter/linter-jscs#291]
### Version
Atom 1.8.0  + linter-jscs 4.0.5

### Issue
My editor is blocking on save and I found the causer is `linter-jscs`.

### Recommendation
How about let a sub-process generate the result of jscs, render to the editor view while it's done?

**Comment by wonderbeyond** [comment]
![image](https://cloud.githubusercontent.com/assets/228361/17171601/00811554-5424-11e6-84ba-0d2072191e4e.png)

**Comment by Arcanemagus** [comment]
I'm guessing you are hitting #241, or some variant of that.

Marking this as closed, all JSCS development has [stopped](http://eslint.org/blog/2016/07/jscs-end-of-life) so this will never be fixed. Either downgrade to the JSCS v2 version or preferably move to ESlint.
