### ISSUE TITLE
Crockford `switch` conventions not honored

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [AtomLinter/linter-jscs#300]
### Version
4.0.5

### Issue
[Crockford](http://javascript.crockford.com/code.html) describes switch statements in this way:
```
switch (expression) {
case expression:
    statements
    break;
default:
    statements
    break;
}
```
However, the linter fails and requires that we use this format:
```
switch (expression) {
    case expression:
        statements
    break;
    default:
        statements
    break;
}
```

**Comment by Arcanemagus** [comment]
This would be a JSCS issue, as this package just forwards on messages generated by it. However, all development of JSCS has halted so this will never be fixed. You should migrate over to ESLint if you are able to.

**Comment by Arcanemagus** [comment]
That is assuming you have the `validateIndentation` option enabled, of course 😉.

**Comment by Blackbaud-SteveBrush** [comment]
Thanks, @Arcanemagus
