### ISSUE TITLE
Uncaught RangeError

### ISSUE THREAD

**Issue by halleycarleton** [AtomLinter/linter-jscs#303]
### Version
Atom Version: 1.9.9
System: Ubuntu 16.04.1
Thrown From: linter-jscs package, v4.0.5

### Issue
I frequently get the following error:

```
Uncaught RangeError: Maximum call stack size exceeded
/usr/share/atom/resources/app.asar/src/pane.js:1026
```
**Update:** It seems to be caused by the "Illegal space before opening round brace"`(disallowSpacesInAnonymousFunctionExpressions)` error. If I fix just that issue the error does not pop up.

I end up having to fix the errors manually before saving. (I have "fix on save" enabled)

Here is a [gist containing the error report, the file causing the issue, and my jscs.rc file](https://gist.github.com/halleycarleton/f7d4dca302c96817c5bcda1c4432c31b).
In this case I was pasting an example from inquire.js into my index.js.

**Comment by Arcanemagus** [comment]
Since it is related to a specific rule this sounds like a bug in JSCS, unfortunately all development of JSCS has stopped. I'd recommend moving to ESLint if you are able to as the JSCS team merged in with them.
