### ISSUE TITLE
Array with 50 linter errors causes atom to hang 

### ISSUE THREAD

**Issue by AzRu** [AtomLinter/linter-jscs#307]
### Version

4.0.5 (Atom Version 1.10.2, Mac OS 10.12)
### Issue

I have an array of ~200 objects containing 'mock data'. Each object has 3 key-value pairs. One of these is a url string which is causing 'line must be at most 80 char' errors for ~50 of these objects. Whenever I load this file, Atom hangs for a good 30-60s and the keep waiting prompt comes up. Whenever I make modifications to the file it happens. Even when using //jscs:disable(& //jscs:enable) around the array this happens. Makes Atom unusable when editing the file and the plugin is enabled. 

The URLs contain sensitive info or I'd share that. Let me know if you need more info.

**Comment by Arcanemagus** [comment]
This sounds like a performance issue with JSCS. The best solution is to just move over to ESLint, as all development on JSCS has stopped.

If you can't do that for some reason then you can either figure out which JSCS rule is causing the massive performance hit and disable that, or submit a PR here moving the execution of JSCS to a separate thread. Moving it to another thread wouldn't solve your performance issue, but it would make it not kill the editor while it is running.

I personally have zero interest in working on that as JSCS is no longer being worked on so there isn't much point in putting effort into a dead linter.

**Comment by Arcanemagus** [comment]
Marking this as closed, JSCS development is dead, and it seems none of the people still using it are interested in implementing this functionality.
