### ISSUE TITLE
Editor locking up (completely freezes) with ES6 decorator syntax

### ISSUE THREAD

**Issue by cif** [AtomLinter/linter-jscs#313]
### Version
4.1.0

### Issue
Editor completely locks up when it encounters decorator syntax: 

```
@autobind
  updateState(e) {
    this.setState({ data: e.target.value });
  }
```

Verified this plugin was the issue, fine when disabled and locked when enabled. Updated to latest version.

Do I need to update any of the modules? Didn't happen before and switched to the branch on which I'm upgrading some tooling.

**Comment by cif** [comment]
Best solution is to update to https://github.com/AtomLinter/linter-eslint.

**Comment by Arcanemagus** [comment]
Very much so, JSCS development is completely dead and I suspect that this is the same performance bug in JSCS v3 that a few other issues are related to.
