### ISSUE TITLE
Fixes on save regardless of setting

### ISSUE THREAD

**Issue by robneu** [AtomLinter/linter-jscs#314]
### Version
3.0.1

### Issue
Ever since the 3.0.1 update the fix on save setting doesn't seem to actually do anything. Whether it's checked or unchecked the fixing happens on every save.

**Comment by Arcanemagus** [comment]
Are you sure this is the right project? There was no v3.0.1 of `linter-jscs`.

I just published v3.0.1 of `linter-jshint`... but that doesn't have a fix on save functionality 😕.

**Comment by robneu** [comment]
Ah, sorry I grabbed the version out of the wrong project because I was looking at both of them. It's version `4.1.0.` and the issue does seem to be in this project as far as I can tell.

**Comment by Arcanemagus** [comment]
Hmmm, I'm not seeing this, and [this line](https://github.com/AtomLinter/linter-jscs/blob/v4.1.0/src/linter-jscs.js#L180) should make it impossible, but I'll try to double check.

As a sanity check what does `atom.config.get('linter-jscs.fixOnSave')` give you if you run it in the Console of the Developer Tools?

**Comment by robneu** [comment]
Well, I uninstalled and reinstalled the package and it seems fine now. Gremlins, perhaps? 😔

**Comment by Arcanemagus** [comment]
Interesting, I'm going to mark this as closed then, thanks for reporting back!
