### ISSUE TITLE
jscs:ignore maximumLineLength does not work for commented out lines

### ISSUE THREAD

**Issue by ryanrishi** [AtomLinter/linter-jscs#316]
### Version
4.1.0

### Issue
`jscs:ignore maximumLineLength` does not work for commented out lines. For example, if I have this:
```javascript
        // console.debug('this is a really long message that doesn't really serve a purpose and would be really annoying to see in the dev console) // jscs:ignore maximumLineLength
```
linter-jscs is still showing a warning (I have the maximumLineLength set to 120).

**Comment by ryanrishi** [comment]
If I put this in my .jscsrc:
```json
"maximumLineLength": {
    "value": 120,
    "allExcept": ["comments"]
}
```
it does work. I'll use that as a workaround.

**Comment by Arcanemagus** [comment]
Two things to note:

* This project is simply an integration of JSCS into Atom
* All development of JSCS has stopped, you should look into migrating to ESLint if at all possible.
