### ISSUE TITLE
How to lint on only save (not on keypress)?

### ISSUE THREAD

**Issue by adamzerner** [AtomLinter/linter-jscs#320]
http://stackoverflow.com/questions/41540014/how-to-run-jscs-on-save-only-not-on-keypress-in-atom

----
Edit by @Arcanemagus

I'm reposting the question posted over there here so this doesn't just look like spam:

> I'm using https://github.com/AtomLinter/linter-jscs. The docs say:
> `It will lint on edit and/or on save`
>It seems that it lints on edit and save all the time. I don't see a way to configure it to lint on only save.

**Comment by Arcanemagus** [comment]
First of all you really should be looking into moving to ESLint ([linter-eslint](https://atom.io/packages/linter-eslint)) as _all_ development on JSCS has stopped.

As for your question, you can configure this behavior in the Linter package by disabling On-the-fly linting there. This package is simply a service provider allowing linting of code through JSCS, the Linter package is what controls _when_ it is ran, and how its results are displayed to the user.

**Comment by adamzerner** [comment]
Ah ok, thanks.
