### ISSUE TITLE
How to work like your GIF picture?

### ISSUE THREAD

**Issue by boloog** [AtomLinter/linter-jscs#329]
### Version
[linter-jscs 4.1.2 ](https://atom.io/packages/linter-jscs)

### Issue
atom How to install this plugin will not be configured for the following error，thank you。
`$('#box').before('content');`
This is wrong Invalid quoe mark found
`$( "#box" ).before( "22222" );`
This is not a problem

**Comment by Arcanemagus** [comment]
It sounds like you are trying to configure JSCS, you'll need to specify an option in your `.jscsrc` file to do that.

I would _highly_ recommend moving to ESLint though as JSCS development is entirely dead.
