### ISSUE TITLE
unexpected token &lt; on any jsx file

### ISSUE THREAD

**Issue by mderazon** [AtomLinter/linter-jscs#33]
When working in react, `jscs` immidiately throws an error with the first html syntax it sees even if it's a valid jsx element:

![screen shot 2015-02-22 at 3 40 14 pm](https://cloud.githubusercontent.com/assets/717076/6318696/3fa372ec-baa9-11e4-82a7-27d08ffbacac.png)

**Comment by mderazon** [comment]
actually, since I have a dedicated jsx linter, I would rather just cancel the check on jsx files. Is it possible ?

**Comment by iam4x** [comment]
@mderazo You have to enable harmony option in linter-jscs parameters.
