### ISSUE TITLE
how to disable validateQuoteMarks rule?

### ISSUE THREAD

**Issue by Dawa12** [AtomLinter/linter-jscs#331]
### Version
4.1.2

### Issue
I cannot remove the validateQuoteMarks rule. I've created a .jscrc file and pointed to it from the JSCS package settings.

I followed the documentation and made this attempt at removing the rule, but it doesn't work: 

![image](https://cloud.githubusercontent.com/assets/10649550/23804180/fa09daca-0586-11e7-9a97-89174126ac36.png)

I have a large JSON object and I think JSCS maxes out after 50 errors since it doesn't catch my other errors below the JSON object. 

Thanks in advance for the help :)

**Comment by Arcanemagus** [comment]
You'll need to configure that in JSCS, this is just a wrapper around that.

Also, you _really_ should be moving over to ESLint, JSCS development has been halted permanently since the team merged into ESLint.

**Comment by Dawa12** [comment]
thanks @Arcanemagus, I'll checkout ESLint then
