### ISSUE TITLE
Add some delay of validation to increase usability while writing code

### ISSUE THREAD

**Issue by danillewin** [AtomLinter/linter-jscs#336]
There are a lot of jscs erros to be found, while writing code, that are fixed when line is done. Can we validate code with some delay, after stop writing?

**Comment by danillewin** [comment]
That's what I mean

![image](https://user-images.githubusercontent.com/6246972/27084576-117ba86e-5055-11e7-9267-dbcf178a1e4e.png)

**Comment by Arcanemagus** [comment]
You can customize the delay in the settings for Linter, as that is what is actually running this package. All this package does is provide a service.

Personally I set the delay to 1500 ms, the default is 300 ms.

**Comment by danillewin** [comment]
Thank you)
