### ISSUE TITLE
Package doesn't run(?) and affect Atom core (file tabs stops working)

### ISSUE THREAD

**Issue by ludwighogstrom** [AtomLinter/linter-jscs#34]
Hi, I have an issues with linter/linter-jscs. If the package is activated the Atom file tabs stops working. 

Atom developer tools console spits out: 
activate linter-jscs - /Users/ludwigh/.atom/packages/linter-jscs/lib/init.coffee:30 activate linter-jscs

The linter-jscs doesn't seems to run at all.

Running: 
OS X 10.10.2 
Atom 0.182.0

Have tried to reinstall the package but the problem still occur.

**Comment by SerenadeX** [comment]
I am also seeing this.  I installed linter-jscs but it isn't doing anything.  I'm not having problems with file tabs though.  They seem to still be working fine.

**Comment by ludwighogstrom** [comment]
Hi, updated to linter-jscs version 1.8.0 but the problem is still there. 

Here's some more info about the tab problem:

Most files doesn't spawn a file tab (with the file name). Instead the tab of the current file stays. However, the content of the file shows.

It seems related to being able to open files with single / double click? Files that for some reason needs double click doesn't get a tab. Single click files works as expected.

Can't detect any pattern for file types. Just have normal files as *.js and *.html etc.
