### ISSUE TITLE
Invalid plug-in

### ISSUE THREAD

**Issue by mcya** [AtomLinter/linter-jscs#343]
### Issue
What else do you need to configure in ATOM? When I install this plug-in, there will be no errors when the syntax is wrong. Excuse me, how can I solve this problem?

### 中文

在ATOM中，还需要做什么配置吗？我装了这个插件之后，当语法发生错误的时候，也无法出现错误的提示。请问，这个要怎么解决？
--百度翻译~~

**Comment by Arcanemagus** [comment]
Do you have [linter](https://atom.io/packages/linter) installed and enabled? Can you run `Linter: Debug` from the Command Palette?

**Comment by mcya** [comment]
Thanks
