### ISSUE TITLE
The module causes hang on big javascript file, 10k+ lines

### ISSUE THREAD

**Issue by sinclairfr** [AtomLinter/linter-jscs#346]
### Version
4.1.3

### Issue

I had issues with opening this big javascript files such as this one: [https://raw.githubusercontent.com/sinclairfr/medos-finest/master/background-single-line.js](url)

It causes **hang**, **freezes** and I have no option but to **force-quit** Atom.

I have singled out **linter-jscs** as the source of the problem by disabling all my loaded modules and re-enabling them one by one.

Is there a way to disable linter-jscs when a file is too big?

**Comment by Arcanemagus** [comment]
JSCS development is officially dead, please migrate to ESLint. (`linter-eslint` does linting work in a separate thread which is the solution to this issue.)
