### ISSUE TITLE
Not showing errors in actual line

### ISSUE THREAD

**Issue by ejgutierrez74** [AtomLinter/linter-jscs#357]
### Version
4.1.3

### Issue
Its some kind of feature request. When i clic enter and began to write a new code line of javascript it appears a signal of error ( ex: missing ; as i use the google preset)... I think it has to left users to end the line and then apply the linter ( or at least an option). Or for example when you begin to declare a variable....
![imagen](https://user-images.githubusercontent.com/11474846/46526938-020c3380-c890-11e8-971e-4b3178f09980.png)

Thats a little annoying as you cant ever write a line of code without errors....

**Comment by Arcanemagus** [comment]
When an error is highlighted a range of the text is marked by Atom. As you type within that original range, the marked area is automatically expanded until the range is updated on the next update of the diagnostic results. This is the intended behavior so you can either pause long enough for the results to update, _or_ remember to type the `;` 😉.
