### ISSUE TITLE
Add new presets

### ISSUE THREAD

**Issue by ejgutierrez74** [AtomLinter/linter-jscs#358]
### Version
4.1.3

### Issue
Add standard and ESLint presets.

**Comment by Arcanemagus** [comment]
No such presets exist in the last version of JSCS that will ever be produced:
[JSCS v3.0.7 presets](https://github.com/jscs-dev/node-jscs/tree/v3.0.7/presets)

For that matter, `standard` didn't even exist when JSCS development stopped, so I'm not sure what you are even talking about. You should be using ESLint to lint your JavaScript code.
