### ISSUE TITLE
Disable cameCase errors

### ISSUE THREAD

**Issue by razagill** [AtomLinter/linter-jscs#38]
Hi,
How can I disable the warning `all identifiers must be camelcase or upper_case`. I tried setting `"requireCamelCaseOrUpperCaseIdentifiers": "ignoreProperties"` in my .jscsrc file but that doesn't work.

**Comment by iam4x** [comment]
What is your `.jscsrc` path and your edited file?

Could you show your `.jscsrc` content?

Thanks

**Comment by razagill** [comment]
It's placed at the root of my project folder with the following content.
`{
  "requireCamelCaseOrUpperCaseIdentifiers": "ignoreProperties"
}`

**Comment by iam4x** [comment]
You have to remove the rule entirely, http://jscs.info/rules.html

**Comment by razagill** [comment]
Okay I added the rule, but now I don't see any errors from jscs at all. Here is my .jscsrc file:
`{
  "requireCamelCaseOrUpperCaseIdentifiers": false
}`
It seems jscs is only following that one rule and not the preset I selected.

**Comment by trvra** [comment]
Try adding the preset to to your .jscsrc file like this:
````
{ 
  "preset": "google", 
  "requireCamelCaseOrUpperCaseIdentifiers": false
}
````
If I understand what's going on correctly, it seems like linter-jscs is ignoring the preset option in its settings because you are supplying a .jscsrc, which does not include a preset.

**Comment by iam4x** [comment]
Exactly @trvra
