### ISSUE TITLE
Support jscs-jsdoc

### ISSUE THREAD

**Issue by Deathspike** [AtomLinter/linter-jscs#39]
Adding a dependency to `jscs-jsdoc` would be nice:

https://www.npmjs.com/package/jscs-jsdoc

It's an extension for JSCS and validates JSDoc notations as per your configuration.

**Comment by iam4x** [comment]
@Deathspike have you tried to `npm install --save-dev jscs-jsdoc` in your project with a `.jsrc` in  your project?

**Comment by iam4x** [comment]
poke @Deathspike

**Comment by Thrilleratplay** [comment]
I was curious about this too.  According to the Developer Tools, Atom could not find jscs-jsdoc if it was installed as a dev dependency for my project nor if installed globally.  It  however did work after installing it as a dev dependency for linter-jscs under ~/.atom/packages/linter-jscs

**Comment by piotr-cz** [comment]
It's because `jscs` and it's plugins are being required from within the package's `node_modules`, not project's `node_modules`.

Probably it should be like this, the question is how to handle jscs plugins management in the package.

**Comment by iam4x** [comment]
@piotr-cz It's pain in the ass, we have support of project `node_modules` with `linter-eslint`.

Should be easier to declare it as dependancy of the package.

**Comment by piotr-cz** [comment]
Yes, but jscs plugins are defined per project

**Comment by piotr-cz** [comment]
After update to v2, linter-jscs is using jscs v2 which seems to parse my JSDocs. In  the [chngelog](http://jscs.info/changelog.html#version-2-0-0-https-github-comjscs-devnode-jscscomparev1-13-1-v2-0-0) they mention that they added new JSDoc rules, but to me it seems that whole jscs-jsdoc plugin has been merged into jsdoc and just started working by itself.

Reference: jscs > [JSDoc](http://jscs.info/rule/jsDoc.html)

**Comment by iam4x** [comment]
Great :+1:
