### ISSUE TITLE
My Atom now hangs when I start it.

### ISSUE THREAD

**Issue by MaiMariarti** [AtomLinter/linter-jscs#390]
### Version
4.2.1

### Issue
My Atom now hangs when I start it.
I created a folder in My Document directory called “jQuery” and in that folder, I created a file called jQuery.js and pasted the entire source code of jQuery.js library, in a non-minimized format, using Notepad++.
Now when I open jQuery.js with Atom, it loads the file and I can see it on the screen, but it just hangs and consumes 13% of one of my cores. After a while a message pops-up saying “Editor not responding”, with the option of “Force close” , or “Keep waiting”.
I disabled all Community add-ons and re-enabled them one by one. 
The culprit was linter-jscs.
I uninstalled it. 
Problem solved. 
Don't care if you fix it or not. Will not use it again.

**Comment by Arcanemagus** [comment]
JSCS hasn't been [maintained for _years_](https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2), this provider is only around for things that are stuck using it for legacy reasons.

If you want to investigate it I'd be happy to review a PR, but if at all possible you should _definitely_ be moving to ESLint.

**Comment by MaiMariarti** [comment]
ESLint has been deprecated.

**Comment by Arcanemagus** [comment]
You might want to let the ESLint team and the entire JavaScript community know, since they didn't get the memo on that.

**Comment by MaiMariarti** [comment]
All I know is under Atom/install packages, I type "ESLint" and it comes out with a list.
1st on the list is eslint 0.15.0 and it says "DEPRICATED" in capital letters!  
It didn't surprise me, since it hasn't been updated for 5 years.  
Check it out for yourself if in doubt. 
I've installed "linter-eslint" and this chapter of my life is closed, just like this issue.
