### ISSUE TITLE
Formatting?

### ISSUE THREAD

**Issue by ColCh** [AtomLinter/linter-jscs#47]
Via this article: [Auto-formatting JavaScript Code Style
](https://medium.com/@addyosmani/auto-formatting-javascript-code-style-fe0f98a923b8)

Really awesome feature :mouse:

**Comment by iam4x** [comment]
@ColCh I can't do this with base linter API.

It's a nice feature, I will do create an Atom package for it! :+1:

**Comment by carlosagsmendes** [comment]
@iam4x are you working on the auto-formatting?

**Comment by Pofigizm** [comment]
https://atom.io/packages/jscs-fixer

**Comment by ColCh** [comment]
@Pofigizm brilliant :+1:

**Comment by iam4x** [comment]
Great @Pofigizm I'll add a note on readme about this ;)
