### ISSUE TITLE
Linter has stopped working

### ISSUE THREAD

**Issue by smlombardi** [AtomLinter/linter-jscs#52]
I had been using it for weeks successfully.  I just installed John Papa's "hottowel" generator.

I wound up ditching the project created with it as insanely complicated for what I need and went about simply creating a plain single-page angular app from scratch. However, now I see this: `The linter binary 'jscs' cannot be found.` at the bottom of the window.

I checked Terminal with `which jscs` and got `/usr/local/bin/jscs` as expected.  I then put this path into the jscs linter settings (it had been set to the default.  The JSCS version is 1.13.1.

I opened an old project, and the error was _not_ there.  However, no errors displayed in the gutter.  I forced an error, and if it put my cursor in the (non-indicated) error I could see the box
![screen shot 2015-05-05 at 2 05 58 pm](https://cloud.githubusercontent.com/assets/835148/7479491/f92432f6-f32f-11e4-82fb-37725ab8b9c9.png)

What happened , and how do I get it functioning again?

**Comment by iam4x** [comment]
Remove jscs path and try to install locally into your project jscs `npm i --save-dev jscs`

**Comment by Eschon** [comment]
I have a similar problem, I just installed the package and I didn't have installed jscs before. Installing it locally also didn't work.

**Comment by nelsonmenezes** [comment]
"Same here". Other linters seem to work fine (java, csshint, jshint).

**Comment by iam4x** [comment]
I can reproduce, I will debug this :+1:

**Comment by edersohe** [comment]
+1

**Comment by zing321** [comment]
Any updates on this? I went back to using sublime because of the issue.

**Comment by smlombardi** [comment]
FWIW, it does seem to work, although it's not giving me gutter
indications.  I switched the linter prefs to report all errors at the
bottom of the screen instead of inline, and I am getting jscs errors

**Comment by iam4x** [comment]
I have finally found severals problems about this, I can now get a fix. It's a bit harder than I thought to debug :)

**Comment by iam4x** [comment]
Update your linters tell me if it's good for you.

If it's not, list the linters used and their configuration thanks.

**Comment by zing321** [comment]
sweet, it works! Thanks for the fix.

**Comment by kand** [comment]
:+1:
