### ISSUE TITLE
`preset` should default none if there is a .jscsrc file

### ISSUE THREAD

**Issue by stevemao** [AtomLinter/linter-jscs#54]
`preset` is usually defined in .jscsrc file so if one present, user properly doesn't want to define any preset.

**Comment by trvra** [comment]
The `preset` setting is already ignored if a .jscsrc or .jscs.json file is found, but the settings could use an improvement to make this more clear.

Is there any value in having a "none" preset, if the option exists to disable linter-jscs if no config file is found?

**Comment by iam4x** [comment]
Should be fixed with 2.0.0!
