### ISSUE TITLE
'Message type' setting seems to be ignored - errors are always in red

### ISSUE THREAD

**Issue by markwainwright** [AtomLinter/linter-jscs#58]
I've tried changing the 'message type' setting and no matter what, JSCS errors always show up as `error`-level - i.e. in red. I've also tried abandoning my local package.json `jscsConfig` and using a few of the presets instead and it always goes to 'error'.

Is there anything I'm missing here, or is this a bug? I would love my JSCS issues to show as 'warning' or 'info'.

**Comment by iam4x** [comment]
Should be fixed with 2.0.0 version.
