### ISSUE TITLE
Package.activateConfig is deprecated.

### ISSUE THREAD

**Issue by pavlo-yuriychuk** [AtomLinter/linter-jscs#61]
Use a config schema instead. See the configuration section
of https://atom.io/docs/latest/hacking-atom-package-word-count and
https://atom.io/docs/api/latest/Config for more details
```
Package.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:265:11)
Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:236:14)
<unknown> (/usr/share/atom/resources/app.asar/src/package.js:221:30)
Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
Package.activate (/usr/share/atom/resources/app.asar/src/package.js:213:14)
PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:452:21)
```

Atom version 1.0

**Comment by erikdonohoo** [comment]
Atom has disabled this package running 1.0.0 or higher.  Until the api compatibility is fixed no one can use linter-jscs and we LOVE linter-jscs

**Comment by jacinto123** [comment]
Yeah its not working for me either...has this project been abandoned?

**Comment by k2b6s9j** [comment]
I'll fix this issue when I get home.

**Comment by iam4x** [comment]
Are you sure this is thrown by linter-jscs? Because we do use a config schema.

**Comment by erikdonohoo** [comment]
If you are running 1.0.0, you will see the problem.  Whether the mentioned issue is the only issue is unclear, but linter-jscs does not work on atom 1.0.0.  The package is grayed out when you search for it (most likely because atom detects it is using deprecated APIs is my guess).  Atom doesn't let you install it

**Comment by iam4x** [comment]
I can 100% confirm we don't use a config schema, and this error is not thrown on my Atom.

Try to quit Atom `apm uninstall linter-jscs && apm install linter-jscs`
