### ISSUE TITLE
Enable esnext option for/ in specific file

### ISSUE THREAD

**Issue by piotr-cz** [AtomLinter/linter-jscs#67]
I'm working on application where most of the javascript files are intended for frontend, so I'd prefer have option exnext disabled.

However I'd like to use ES6 features at least in the gulpfile that is run by io.js.

I've tried using `/* jscs:enable esnext */` and `"use babel";` on top of the file but that didn't work.
Probably because this is syntax for rules, and _esnext_ is an CLI option.

I have a gut feeling that there may be some obstacles to implement _esnext_ option per file in jscs project, but maybe it makes more sense to do so in the linter-jscs, as it probably lints each file separately, like it's possible in jshint?

**Comment by iam4x** [comment]
Use `esnext: true` into your `.jscsrc` :)

**Comment by piotr-cz** [comment]
Maybe it would be possible to search for string `/* jscs:esnext */` in target file in [linter.jscs.coffee](https://github.com/AtomLinter/linter-jscs/blob/master/lib/linter-jscs.coffee#L72) and add an argument

pseudocode:

```coffee
@cmd = "#{@cmd} --esnext" if fs.readFileSync(file).search('/* jscs:esnext */') != -1
```

**Comment by iam4x** [comment]
@piotr-cz If you want to fork and use your own with the line you added it's up to you. But this is not the scope of the package.
