### ISSUE TITLE
Add the ability to specify a single global .jscsrc file.

### ISSUE THREAD

**Issue by mattcollier** [AtomLinter/linter-jscs#70]
As I understand it, we currently have the option of choosing from one of the hard coded presets, or specifying a custom configuration for a project by placing a .jscsrc file in the project root.

I would like to see an option that allows us to specify a single .jscsrc file that will be used across all projects, like a preset.  This config should be overidden by a project .jscsrc just like a preset.

**Comment by iam4x** [comment]
@mattcollier Add an `.jscsrc` file at the root directory from all your projects. For instance in your os home directory.
