### ISSUE TITLE
linter-jscs is trying to lint .jscsrc file

### ISSUE THREAD

**Issue by varemenos** [AtomLinter/linter-jscs#72]
For some reason after the update to v2 I'm getting errors from linter-jscs. It seems like it's trying to lint the .jscsrc file and is obviously failing.

![screenshot from 2015-07-28 17-20-40](https://cloud.githubusercontent.com/assets/626343/8933723/0363e64e-354d-11e5-9dbc-ea56aff4c3b1.png)

**Comment by roelvanhintum** [comment]
This has just been updated in 2.0.1, but updating leads me into the next issue...
![screen shot 2015-07-28 at 16 21 54](https://cloud.githubusercontent.com/assets/1023734/8933754/cfa5d52c-3544-11e5-9908-6de27fbe5985.png)

**Comment by piotr-cz** [comment]
@roelvanhintum There is already new issue for that #73

**Comment by varemenos** [comment]
I'm closing this issue, track #73 for the "path" issue introduced in 2.0.1.
If anyone else is still having this issue, let us know so we can reopen it.
