### ISSUE TITLE
Path is not defined error

### ISSUE THREAD

**Issue by Eschon** [AtomLinter/linter-jscs#73]
After the update to `linter-jscs 2.0.1` I keep getting an error every time linter tries to lint the file.
![screen shot 2015-07-28 at 16 39 52](https://cloud.githubusercontent.com/assets/11647830/8934333/77b5c1bc-3547-11e5-86ad-96fd0d569181.png)

I'm using linter 1.2.4, Atom 1.0.2 and OS X 10.10.4

**Comment by piotr-cz** [comment]
same here

**Comment by cttibbetts** [comment]
Same issue, but on Windows 7.

**Comment by piotr-cz** [comment]
Isn't that rather [line 127](https://github.com/AtomLinter/linter-jscs/blob/v2.0.1/index.js#L127)?

**Comment by globexdesigns** [comment]
+1 Mac OS

**Comment by carlhopf** [comment]
+1 OS X

**Comment by DavidOdere** [comment]
+ 1 Mac Os

**Comment by markwainwright** [comment]
+1 OS X

**Comment by samtsai** [comment]
Anyone still getting the errors post the update?
