### ISSUE TITLE
JSCS Config with comments

### ISSUE THREAD

**Issue by MikeMcElroy** [AtomLinter/linter-jscs#78]
Some teams have their config files peppered with comments, and it throws an exception in the `JSON.parse` call.  Could we possibly find some way to parse config files with comments in them?

**Comment by MikeMcElroy** [comment]
Maybe using something like https://github.com/getify/JSON.minify

**Comment by elijahsmith** [comment]
to clarify the issue a bit: vanilla jscs accepts comments in the .jscsrc file, and even describes that as acceptable at http://jscs.info/overview.html: ".jscsrc (which is a just JSON with comments)"

**Comment by elijahsmith** [comment]
the jscs behavior:

https://github.com/jscs-dev/node-jscs/blob/master/lib/cli-config.js#L66-L73

**Comment by iam4x** [comment]
Fixed thank's for the link @elijahsmith !

**Comment by elijahsmith** [comment]
sweet, thank you @iam4x
