### ISSUE TITLE
Presets being used even when config only checked.

### ISSUE THREAD

**Issue by steveoh** [AtomLinter/linter-jscs#80]
I have a `.jscsrc` file which isn't being found it seems like since the errors are being thrown from the preset. This is also odd since I have the config only checked.

jscs version 2
linter-jscs 2.0.3
windows

**Comment by Eschon** [comment]
Do you use a preset in your `.jscsrc`? If so maybe the preset has been changed.
I used `mdcs` in my config and suddenly there were a lot of new errors after the update. At first I thought there might be an error with `linter-jscs` but after investigating a little I realised that `mdcs` has changed a few rules.

**Comment by steveoh** [comment]
[we do not use any preset for that reason](https://github.com/agrc/wri-web/blob/master/.jscsrc)

**Comment by Eschon** [comment]
Have you tried the release that came out 6h ago?
That fixed it for me.

**Comment by iam4x** [comment]
Yes should be fixed with 949dc142f0ae86aec83ac9a6395402a913594d05
