### ISSUE TITLE
Feature request: Configure what configuration file to look for

### ISSUE THREAD

**Issue by vegar** [AtomLinter/linter-jscs#85]
I have an issue with the way `linter-jscs` looks for configuration file. 

In our project, we have something similar to the following structure:

     root
        / subproject
            - package.json
            / node_modules
            / app
        / second subproject
            - package.json
            / node_modules
            / app

We want to enforce the same styles for all our JavaScript across the entire project by having a `.jscsrc` file on the project root.

     root
        - .jscsrc     <-- global style rules
        / subproject
            - package.json
            / node_modules
            / app
        / second subproject
            - package.json
            / node_modules
            / app

When checking styles from command line using `jscs ./subproject/app`, jscs will use the right configuration. But inside atom, it will always pick up on the package.json file in the subproject when checking files inside the app folders.

So I wan't a way to configure myself out of this issue.

Today, linter-jscs have a fixed set of config files that it search for:

        const configFiles = ['.jscsrc', '.jscs.json', 'package.json'];

        // Search for project config file
        let config = findFile(filePath, configFiles);

If the configFiles-array could be a configuration option, I could remove package.json from the list.

**Comment by iam4x** [comment]
@vegar Removing `package.json` in the array solves the issue?

I'm okay of having this as an option if it works

**Comment by vegar** [comment]
Yes, it will resolve my issue.

Currently, I only get a lot of `diallowKeywordsOnNewLine - Unsupported rule: disallowLeftStickedOperators...` errors, which I'm not sure why I get, but I guess it's because of missing configuration inside the package.json, which again makes it use the one in my home directory, which again is full of deprecated rules for some reason...

**Comment by porteta** [comment]
I think the issue is really this section:

```
// Reset config if `jscsConfig` is not found in `package.json`
if (config && config.indexOf('package.json') > -1) {
  const { jscsConfig } = require(config);
  if (!jscsConfig) config = null;
}
```

Which sets the config to null if there's no jscsConfig in the first package.json file found. Instead of setting it to null, could you continue searching up the directories until another config file is found? That way we could use different jscs config file types for different projects, instead of limiting it in the settings.

**Comment by vegar** [comment]
+1

That's even more 'cleverer'!

**Comment by acusti** [comment]
@porteta The package relies on the `findFile` helper function provided by atom-linter, which doesn’t make it easy to resume searching up the directories in that way.

An easier implementation might be iterating over the config file names from most to least specific using the `findFile` helper function on individual names instead of an array of names. I am running into this issue in a project using numerous private NPM modules; the package.json of a particular module has nothing to do with JSCS configuration, but it is closer to the final file in the directory hierarchy, so it prevents my `.jscsrc` file from being found. Searching first for a `.jscsrc`, then `.jscs.json`, then `package.json` would avoid prematurely truncating `findFile`’s search with an insufficiently specific match.

**Comment by astoilkov** [comment]
+1

I have experienced the same issue. Spend 20 minutes to understand that the package.json in subdirectory was preventing it to find the `.jscsrc` file in the root directory.

I think the @acusti solution is the right way to go.

**Comment by jonek** [comment]
My project structure prevents ```.jscsrc``` to be found for exactly the same reasons as @acusti described.  For me this is a blocker bug.

**Comment by stdavis** [comment]
I'm also running into this bug. I have a `package.json` before my `.jscsrc` in my directory structure.

**Comment by vegar** [comment]
The solution proposed by @acusti will probably solve the issue for most people, but I'm not sure it's the best solution.

I think that the 'closest' configuration should always 'win'. 

The proposal, as I understand it, is that a local `package.json` configuration should yield for a `.jscsrc` file further up in the  folder hierarchy. But that's not logical, is it?

The _real_ problem here, is that an `package.json` file without a `jscsConfig`-configuration block still is detected as a configuration file. I understand that solving this is not straight forward, but I still think that's the issue that should be solved.

**Comment by vegar** [comment]
One more thing on priority. Jscs cli it self actually (prioritize project.json over .jscsrc)[http://jscs.info/overview.html#cli]:

> If there is no --config option specified, jscs it will consequentially search for jscsConfig option in package.json file then for .jscsrc (which is a just JSON with comments) and .jscs.json files in the current working directory then in nearest ancestor until it hits the system root.

But they [ignore package.json](https://github.com/jscs-dev/node-jscs/blob/16d6c06b288d8be8091f646b666303ea32482dd8/test/specs/cli-config.js#L60
) if it doesn't contain any configuration:

        it('should use another config source if package.json contains no config', function() {
            var config = configFile.load(null, './test/data/configs/mixedWithEmptyPkg');

            assert.equal(config.from, '.jscsrc');
        });

Would it be an option to use [`cli-config.js`](https://github.com/jscs-dev/node-jscs/blob/master/lib/cli-config.js) from the `jscs` package instead of the [`findFile`](https://github.com/AtomLinter/atom-linter/blob/master/lib/helpers.coffee#L97) feature from the `atom-linter`?

**Comment by abhishekdev** [comment]
:+1:
