### ISSUE TITLE
Configure .jscsrc per project

### ISSUE THREAD

**Issue by LuisHerranz** [AtomLinter/linter-jscs#93]
I'd like to have a .jscsrc per project. Is that possible?
So far only ~/.jscsrc has worked for me.

**Comment by Eschon** [comment]
Having a .jscsrc file in my project folder works for me.
Maybe your problem has something to do with #85.

**Comment by LuisHerranz** [comment]
I don't know but adding a package.json and a jscsConfig option there did the trick.
