### ISSUE TITLE
Config file location logic is wrong

### ISSUE THREAD

**Issue by zyklus** [AtomLinter/linter-jscs#96]
Two issues with the config file location logic:

- [ ] Load order is wrong.  [jscs source](https://github.com/jscs-dev/node-jscs/blob/master/lib/cli-config.js#L13) has it as `['package.json', '.jscsrc', '.jscs.json']`, the linter has it as `['.jscsrc', '.jscs.json', 'package.json']`
- [ ] `package.json` "ignoring" is wrong.  If `package.json` doesn't contain `.jscsConfig`, it should continue searching up the directory tree, _not_ immediately switch to searching `$HOME`

**Comment by abhishekdev** [comment]
This is related to #85. I hope this is fixed soon.

**Comment by acusti** [comment]
The behavior is made consistent with JSCS in PR #87 (by using the actual `jscs/lib/cli-config` module `load` method from the JSCS package).

**Comment by Arcanemagus** [comment]
Marking as closed per the above comment.
