### ISSUE TITLE
ignoring nullified rule

### ISSUE THREAD

**Issue by iamstarkov** [AtomLinter/linter-jscs#99]
thank you for this project

Im using [jscs-config-nordnet](https://github.com/nordnet/jscs-config-nordnet) and recently I [nullified](https://github.com/nordnet/jscs-config-nordnet/blob/master/lib/presets/nordnet-preset.json#L14) quote validation from the config, but linter-jscs still complaining:
![screen shot 2015-08-20 at 15 47 29](https://cloud.githubusercontent.com/assets/559321/9384738/c45eb056-4752-11e5-9e25-cfd36c6dcd4e.png)

I tried to restart my atom, but it didnt help, also jscs runned in terminal is giving zero problems

**Comment by casesandberg** [comment]
I cant seem to reproduce this, are you still having this issue?

**Comment by iamstarkov** [comment]
its happened 5 months ago. I will close it, because i have no reproducaple testcase
